///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0007_LocalClientPACSData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseDataC19 recording.
    /// </summary>
    [TestModule("bf31141a-402f-4142-8b5a-c2498a2020e4", ModuleType.Recording, 1)]
    public partial class CloseDataC19 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0007_LocalClientPACSDataRepository repository.
        /// </summary>
        public static TPX_0007_LocalClientPACSDataRepository repo = TPX_0007_LocalClientPACSDataRepository.Instance;

        static CloseDataC19 instance = new CloseDataC19();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseDataC19()
        {
            DataC19ProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseDataC19 Instance
        {
            get { return instance; }
        }

#region Variables

        string _DataC19ProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable DataC19ProcessIDVar.
        /// </summary>
        [TestVariable("c4425f1c-062d-450e-a3c1-d831ea620727")]
        public string DataC19ProcessIDVar
        {
            get { return _DataC19ProcessIDVar; }
            set { _DataC19ProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $DataC19ProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(DataC19ProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
