///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0007_LocalClientPACSData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CScene recording.
    /// </summary>
    [TestModule("2ac1b753-ea7a-4167-b678-598c641de898", ModuleType.Recording, 1)]
    public partial class CScene : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0007_LocalClientPACSDataRepository repository.
        /// </summary>
        public static TPX_0007_LocalClientPACSDataRepository repo = TPX_0007_LocalClientPACSDataRepository.Instance;

        static CScene instance = new CScene();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CScene()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CScene Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Local_ClientData_CScene", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "Test Patient Name, Patient ID, Age, Gender, Accession Num, Study Date, Study Description, Referring Physician and Number of Files", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientCScene' at 32;8.", repo.DicomBrowser.PatientCSceneInfo, new RecordItemIndex(2));
            repo.DicomBrowser.PatientCScene.Click("32;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row22.Cell00100010'.", repo.DicomBrowser.Row22.Cell00100010Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row22.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row22.PatientsName'.", repo.DicomBrowser.Row22.PatientsNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row22.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_CScene') on item 'DicomBrowser.Row22.SomeCell'.", repo.DicomBrowser.Row22.SomeCellInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row22.SomeCellInfo, "Text", "Data_CScene");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0020)') on item 'DicomBrowser.Row23.Cell00100020'.", repo.DicomBrowser.Row23.Cell00100020Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.Cell00100020Info, "Text", "(0010,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient ID') on item 'DicomBrowser.Row23.PatientID'.", repo.DicomBrowser.Row23.PatientIDInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.PatientIDInfo, "Text", "Patient ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='CScene') on item 'DicomBrowser.Row23.CScene'.", repo.DicomBrowser.Row23.CSceneInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.CSceneInfo, "Text", "CScene");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0040)') on item 'DicomBrowser.Row25.Cell00100040'.", repo.DicomBrowser.Row25.Cell00100040Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row25.Cell00100040Info, "Text", "(0010,0040)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Sex') on item 'DicomBrowser.Row25.PatientsSex'.", repo.DicomBrowser.Row25.PatientsSexInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row25.PatientsSexInfo, "Text", "Patient’s Sex");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row25.SomeCell'.", repo.DicomBrowser.Row25.SomeCellInfo, new RecordItemIndex(11));
            Validate.Exists(repo.DicomBrowser.Row25.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0050)') on item 'DicomBrowser.Row13.Cell00080050'.", repo.DicomBrowser.Row13.Cell00080050Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.DicomBrowser.Row13.Cell00080050Info, "Text", "(0008,0050)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Accession Number') on item 'DicomBrowser.Row13.AccessionNumber'.", repo.DicomBrowser.Row13.AccessionNumberInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.DicomBrowser.Row13.AccessionNumberInfo, "Text", "Accession Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row13.SomeCell'.", repo.DicomBrowser.Row13.SomeCellInfo, new RecordItemIndex(14));
            Validate.Exists(repo.DicomBrowser.Row13.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0020)') on item 'DicomBrowser.Row7.Cell00080020'.", repo.DicomBrowser.Row7.Cell00080020Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.DicomBrowser.Row7.Cell00080020Info, "Text", "(0008,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study Date') on item 'DicomBrowser.Row7.StudyDate'.", repo.DicomBrowser.Row7.StudyDateInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.DicomBrowser.Row7.StudyDateInfo, "Text", "Study Date");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='20080421') on item 'DicomBrowser.Row7.Cell20080421'.", repo.DicomBrowser.Row7.Cell20080421Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.DicomBrowser.Row7.Cell20080421Info, "Text", "20080421");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,1030)') on item 'DicomBrowser.Row20.Cell00081030'.", repo.DicomBrowser.Row20.Cell00081030Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.Cell00081030Info, "Text", "(0008,1030)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study Description') on item 'DicomBrowser.Row20.StudyDescription'.", repo.DicomBrowser.Row20.StudyDescriptionInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.StudyDescriptionInfo, "Text", "Study Description");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Scanner-SIEMENS_Exp-200_Pitch-1.2_SlCol-64x0.6mm') on item 'DicomBrowser.Row20.ScannerSIEMENSExp200Pitch12SlCol'.", repo.DicomBrowser.Row20.ScannerSIEMENSExp200Pitch12SlColInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.ScannerSIEMENSExp200Pitch12SlColInfo, "Text", "Scanner-SIEMENS_Exp-200_Pitch-1.2_SlCol-64x0.6mm");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0090)') on item 'DicomBrowser.Row18.Cell00080090'.", repo.DicomBrowser.Row18.Cell00080090Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.DicomBrowser.Row18.Cell00080090Info, "Text", "(0008,0090)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Referring Physician’s Name') on item 'DicomBrowser.Row18.ReferringPhysiciansName'.", repo.DicomBrowser.Row18.ReferringPhysiciansNameInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.DicomBrowser.Row18.ReferringPhysiciansNameInfo, "Text", "Referring Physician’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row18.SomeCell'.", repo.DicomBrowser.Row18.SomeCellInfo, new RecordItemIndex(23));
            Validate.Exists(repo.DicomBrowser.Row18.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0020,0013)') on item 'DicomBrowser.Row34.Cell00200013'.", repo.DicomBrowser.Row34.Cell00200013Info, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.DicomBrowser.Row34.Cell00200013Info, "Text", "(0020,0013)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Instance Number') on item 'DicomBrowser.Row34.InstanceNumber'.", repo.DicomBrowser.Row34.InstanceNumberInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.DicomBrowser.Row34.InstanceNumberInfo, "Text", "Instance Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'DicomBrowser.Row34.SomeCell'.", repo.DicomBrowser.Row34.SomeCellInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.DicomBrowser.Row34.SomeCellInfo, "Text", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,103E)') on item 'DicomBrowser.Row21.Cell0008103E'.", repo.DicomBrowser.Row21.Cell0008103EInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.DicomBrowser.Row21.Cell0008103EInfo, "Text", "(0008,103E)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Series Description') on item 'DicomBrowser.Row21.SeriesDescription'.", repo.DicomBrowser.Row21.SeriesDescriptionInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.DicomBrowser.Row21.SeriesDescriptionInfo, "Text", "Series Description");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='EPX Scene - EPXScene - Scene') on item 'DicomBrowser.Row21.SomeCell'.", repo.DicomBrowser.Row21.SomeCellInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.DicomBrowser.Row21.SomeCellInfo, "Text", "EPX Scene - EPXScene - Scene");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "Local_ClientData_CScene", new RecordItemIndex(30));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
