///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0007_LocalClientPACSData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DataC6 recording.
    /// </summary>
    [TestModule("ff36b11d-4197-42dd-9e57-6ba30e5dca45", ModuleType.Recording, 1)]
    public partial class DataC6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0007_LocalClientPACSDataRepository repository.
        /// </summary>
        public static TPX_0007_LocalClientPACSDataRepository repo = TPX_0007_LocalClientPACSDataRepository.Instance;

        static DataC6 instance = new DataC6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DataC6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DataC6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Local_Client_Data_C6", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "Test Patient Name, Patient ID, Age, Gender, Accession Num, Study Date, Study Description, Referring Physician and Number of Files", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientC6' at 37;9.", repo.DicomBrowser.PatientC6Info, new RecordItemIndex(2));
            repo.DicomBrowser.PatientC6.Click("37;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row23.Cell00100010'.", repo.DicomBrowser.Row23.Cell00100010Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row23.PatientsName'.", repo.DicomBrowser.Row23.PatientsNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_C6') on item 'DicomBrowser.Row23.DataC6'.", repo.DicomBrowser.Row23.DataC6Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row23.DataC6Info, "Text", "Data_C6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0020)') on item 'DicomBrowser.Row24.Cell00100020'.", repo.DicomBrowser.Row24.Cell00100020Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row24.Cell00100020Info, "Text", "(0010,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient ID') on item 'DicomBrowser.Row24.PatientID'.", repo.DicomBrowser.Row24.PatientIDInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row24.PatientIDInfo, "Text", "Patient ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='C6') on item 'DicomBrowser.Row24.CellC6'.", repo.DicomBrowser.Row24.CellC6Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row24.CellC6Info, "Text", "C6");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 11;811.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(9));
            repo.DicomBrowser.VerticalScrollBar.Click("11;811");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,1010)') on item 'DicomBrowser.Row112.Cell00101010'.", repo.DicomBrowser.Row112.Cell00101010Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row112.Cell00101010Info, "Text", "(0010,1010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Age') on item 'DicomBrowser.Row112.PatientsAge'.", repo.DicomBrowser.Row112.PatientsAgeInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.DicomBrowser.Row112.PatientsAgeInfo, "Text", "Patient’s Age");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row112.SomeCell'.", repo.DicomBrowser.Row112.SomeCellInfo, new RecordItemIndex(12));
            Validate.Exists(repo.DicomBrowser.Row112.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 8;22.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(13));
            repo.DicomBrowser.VerticalScrollBar.Click("8;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0040)') on item 'DicomBrowser.Row26.Cell00100040'.", repo.DicomBrowser.Row26.Cell00100040Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.DicomBrowser.Row26.Cell00100040Info, "Text", "(0010,0040)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Sex') on item 'DicomBrowser.Row26.PatientsSex'.", repo.DicomBrowser.Row26.PatientsSexInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.DicomBrowser.Row26.PatientsSexInfo, "Text", "Patient’s Sex");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row26.SomeCell1'.", repo.DicomBrowser.Row26.SomeCell1Info, new RecordItemIndex(16));
            Validate.Exists(repo.DicomBrowser.Row26.SomeCell1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0050)') on item 'DicomBrowser.Row12.Cell00080050'.", repo.DicomBrowser.Row12.Cell00080050Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.DicomBrowser.Row12.Cell00080050Info, "Text", "(0008,0050)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Accession Number') on item 'DicomBrowser.Row12.AccessionNumber'.", repo.DicomBrowser.Row12.AccessionNumberInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.DicomBrowser.Row12.AccessionNumberInfo, "Text", "Accession Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row12.SomeCell'.", repo.DicomBrowser.Row12.SomeCellInfo, new RecordItemIndex(19));
            Validate.Exists(repo.DicomBrowser.Row12.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0020)') on item 'DicomBrowser.Row6.Cell00080020'.", repo.DicomBrowser.Row6.Cell00080020Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DicomBrowser.Row6.Cell00080020Info, "Text", "(0008,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study Date') on item 'DicomBrowser.Row6.StudyDate'.", repo.DicomBrowser.Row6.StudyDateInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.DicomBrowser.Row6.StudyDateInfo, "Text", "Study Date");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='20150327') on item 'DicomBrowser.Row6.Cell20150327'.", repo.DicomBrowser.Row6.Cell20150327Info, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.DicomBrowser.Row6.Cell20150327Info, "Text", "20150327");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,1030)') on item 'DicomBrowser.Row17.Cell00081030'.", repo.DicomBrowser.Row17.Cell00081030Info, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.DicomBrowser.Row17.Cell00081030Info, "Text", "(0008,1030)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study Description') on item 'DicomBrowser.Row17.StudyDescription'.", repo.DicomBrowser.Row17.StudyDescriptionInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.DicomBrowser.Row17.StudyDescriptionInfo, "Text", "Study Description");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row17.SomeCell2'.", repo.DicomBrowser.Row17.SomeCell2Info, new RecordItemIndex(25));
            Validate.Exists(repo.DicomBrowser.Row17.SomeCell2Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0090)') on item 'DicomBrowser.Row16.Cell00080090'.", repo.DicomBrowser.Row16.Cell00080090Info, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.DicomBrowser.Row16.Cell00080090Info, "Text", "(0008,0090)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Referring Physician’s Name') on item 'DicomBrowser.Row16.ReferringPhysiciansName'.", repo.DicomBrowser.Row16.ReferringPhysiciansNameInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.DicomBrowser.Row16.ReferringPhysiciansNameInfo, "Text", "Referring Physician’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DicomBrowser.Row16.SomeCell'.", repo.DicomBrowser.Row16.SomeCellInfo, new RecordItemIndex(28));
            Validate.Exists(repo.DicomBrowser.Row16.SomeCellInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0018)') on item 'DicomBrowser.Row5.Cell00080018'.", repo.DicomBrowser.Row5.Cell00080018Info, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.Cell00080018Info, "Text", "(0008,0018)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SOP Instance UID') on item 'DicomBrowser.Row5.SOPInstanceUID'.", repo.DicomBrowser.Row5.SOPInstanceUIDInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.SOPInstanceUIDInfo, "Text", "SOP Instance UID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='309 values: 1.2.840.113619.2.234.90584417185.12016.1427676918643.1, 1.2.840.113619.2.234.90584417185.12016.1427676918660.7, 1.2.840.113619.2.234.90584417185.12016.1427676918663.8, 1.2.840.113619.2.234.90584417185.12016.1427676918670.9...') on item 'DicomBrowser.Row5.Cell309Values128401136192234905'.", repo.DicomBrowser.Row5.Cell309Values128401136192234905Info, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.Cell309Values128401136192234905Info, "Text", "309 values: 1.2.840.113619.2.234.90584417185.12016.1427676918643.1, 1.2.840.113619.2.234.90584417185.12016.1427676918660.7, 1.2.840.113619.2.234.90584417185.12016.1427676918663.8, 1.2.840.113619.2.234.90584417185.12016.1427676918670.9...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "Local_Client_Data_C6", new RecordItemIndex(32));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
