///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0007_LocalClientPACSData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartDataC8 recording.
    /// </summary>
    [TestModule("d5cab0aa-13b8-4301-8e66-baa920486c3d", ModuleType.Recording, 1)]
    public partial class StartDataC8 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0007_LocalClientPACSDataRepository repository.
        /// </summary>
        public static TPX_0007_LocalClientPACSDataRepository repo = TPX_0007_LocalClientPACSDataRepository.Instance;

        static StartDataC8 instance = new StartDataC8();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartDataC8()
        {
            DataC8ProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartDataC8 Instance
        {
            get { return instance; }
        }

#region Variables

        string _DataC8ProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable DataC8ProcessIDVar.
        /// </summary>
        [TestVariable("778f0381-cc72-4b71-a27b-1e001a9e7534")]
        public string DataC8ProcessIDVar
        {
            get { return _DataC8ProcessIDVar; }
            set { _DataC8ProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe' with arguments '\"C:\\epxData\\InputDirectory\\Client\\Data_C8\"' in maximized mode. Return value bound to $DataC8ProcessIDVar.", new RecordItemIndex(0));
            DataC8ProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe", "\"C:\\epxData\\InputDirectory\\Client\\Data_C8\"", "", true));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser.DicomBrowser' at 246;4.", repo.DicomBrowser.DicomBrowserInfo, new RecordItemIndex(1));
            repo.DicomBrowser.DicomBrowser.DoubleClick("246;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Run DICOMBrowser.exe", new RecordItemIndex(2));
            
            // Open Local_Client_Data_C8
            Report.Log(ReportLevel.Info, "User", "Open Local_Client_Data_C8", new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
