///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0003_zSpaceTracker
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeviceSelect recording.
    /// </summary>
    [TestModule("5dfb559a-e627-4b46-afb8-0f184fc3c260", ModuleType.Recording, 1)]
    public partial class DeviceSelect : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0003_zSpaceTrackerRepository repository.
        /// </summary>
        public static TPX_0003_zSpaceTrackerRepository repo = TPX_0003_zSpaceTrackerRepository.Instance;

        static DeviceSelect instance = new DeviceSelect();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeviceSelect()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeviceSelect Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Check Interaction Device Buttons
            Report.Log(ReportLevel.Info, "User", "Check Interaction Device Buttons", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=88,Height=88}) on item 'ZSpace.Button2'.", repo.ZSpace.Button2Info, new RecordItemIndex(1));
            Validate.CompareImage(repo.ZSpace.Button2Info, Button2_Screenshot1, Button2_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            // HDS_Tracker_Interaction_Device_Select (IMAGE)
            Report.Log(ReportLevel.Info, "User", "HDS_Tracker_Interaction_Device_Select (IMAGE)", new RecordItemIndex(2));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Button2_Screenshot1
        { get { return repo.ZSpace.Button2Info.GetScreenshot1(new Rectangle(0, 0, 88, 88)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Button2_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.98;None;0,0,88,88;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
