///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0011_UserManual
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Cautions1 recording.
    /// </summary>
    [TestModule("5ec79a79-f023-4a3a-9328-1fe75edde235", ModuleType.Recording, 1)]
    public partial class Cautions1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0011_UserManualRepository repository.
        /// </summary>
        public static TPX_0011_UserManualRepository repo = TPX_0011_UserManualRepository.Instance;

        static Cautions1 instance = new Cautions1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Cautions1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Cautions1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Test Caution statements: C.1, C.2, C.3, C.6, C.7, C.8, C.10, C.11, C.15
            Report.Log(ReportLevel.Info, "User", "Test Caution statements: C.1, C.2, C.3, C.6, C.7, C.8, C.10, C.11, C.15", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView' at 842;250.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(1));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView.Click("842;250");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView1' at 598;28.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1Info, new RecordItemIndex(2));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1.Click("598;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C{Decimal}{NumPad1}{Return}' with focus on 'LBL0050000BTrue3DT3DViewerUs'.", repo.LBL0050000BTrue3DT3DViewerUs.SelfInfo, new RecordItemIndex(3));
            repo.LBL0050000BTrue3DT3DViewerUs.Self.EnsureVisible();
            Keyboard.Press("C{Decimal}{NumPad1}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=160,Y=98,Width=440,Height=64}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(4));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4, AVLAVView_Screenshot4_Options);
            Delay.Milliseconds(100);
            
            // C.1 VTP_Labeling_UserManual_Cautions_Professionals / Hazard(s): A3.13, A4.2, A4.3, A4.4, A1.1.2, A1.1.11, A1.1.13, A1.1.14, A1.2.1, A1.2.5, A1.2.7, A1.2.8, A3.1, A3.2, A3.4, A3.5, A3.6, A3.7, A3.8, A3.13, A4.2, A4.3, A4.4
            Report.Log(ReportLevel.Info, "User", "C.1 VTP_Labeling_UserManual_Cautions_Professionals / Hazard(s): A3.13, A4.2, A4.3, A4.4, A1.1.2, A1.1.11, A1.1.13, A1.1.14, A1.2.1, A1.2.5, A1.2.7, A1.2.8, A3.1, A3.2, A3.4, A3.5, A3.6, A3.7, A3.8, A3.13, A4.2, A4.3, A4.4", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=162,Y=168,Width=440,Height=65}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(6));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_2, AVLAVView_Screenshot4_2_Options);
            Delay.Milliseconds(100);
            
            // C.2 VTP_Labeling_UserManual_Cautions_Use2DToCheck / Hazard(s): A1.1.11
            Report.Log(ReportLevel.Info, "User", "C.2 VTP_Labeling_UserManual_Cautions_Use2DToCheck / Hazard(s): A1.1.11", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=157,Y=236,Width=430,Height=36}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(8));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_3, AVLAVView_Screenshot4_3_Options);
            Delay.Milliseconds(100);
            
            // C.3 VTP_Labeling_UserManual_Cautions_SterileUse / Hazard(s): A3.30
            Report.Log(ReportLevel.Info, "User", "C.3 VTP_Labeling_UserManual_Cautions_SterileUse / Hazard(s): A3.30", new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=159,Y=495,Width=445,Height=51}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(10));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_4, AVLAVView_Screenshot4_4_Options);
            Delay.Milliseconds(100);
            
            // C.6 VTP_Labeling_UserManual_Cautions_Sidedness / Hazard(s): A4.2
            Report.Log(ReportLevel.Info, "User", "C.6 VTP_Labeling_UserManual_Cautions_Sidedness / Hazard(s): A4.2", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=160,Y=551,Width=426,Height=38}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(12));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_5, AVLAVView_Screenshot4_5_Options);
            Delay.Milliseconds(100);
            
            // C.7 VTP_Labeling_UserManual_Cautions_StereoAlignment / Hazard(s) A3.10
            Report.Log(ReportLevel.Info, "User", "C.7 VTP_Labeling_UserManual_Cautions_StereoAlignment / Hazard(s) A3.10", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=160,Y=591,Width=434,Height=48}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(14));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_6, AVLAVView_Screenshot4_6_Options);
            Delay.Milliseconds(100);
            
            // C.8 VTP_Labeling_UserManual_Cautions_Use2DToCheck / Hazard(s): A1.1.11
            Report.Log(ReportLevel.Info, "User", "C.8 VTP_Labeling_UserManual_Cautions_Use2DToCheck / Hazard(s): A1.1.11", new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=159,Y=762,Width=437,Height=68}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(16));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot4_7, AVLAVView_Screenshot4_7_Options);
            Delay.Milliseconds(100);
            
            // C.10 VTP_Labeling_UserManual_Cautions_EyeSeparation / Hazard(s) A3.17
            Report.Log(ReportLevel.Info, "User", "C.10 VTP_Labeling_UserManual_Cautions_EyeSeparation / Hazard(s) A3.17", new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.Edit' at 111;12.", repo.LBL0050000BTrue3DT3DViewerUs.EditInfo, new RecordItemIndex(18));
            repo.LBL0050000BTrue3DT3DViewerUs.Edit.Click("111;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.Edit' at 111;12.", repo.LBL0050000BTrue3DT3DViewerUs.EditInfo, new RecordItemIndex(19));
            repo.LBL0050000BTrue3DT3DViewerUs.Edit.Click("111;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{Return}' with focus on 'LBL0050000BTrue3DT3DViewerUs.Edit'.", repo.LBL0050000BTrue3DT3DViewerUs.EditInfo, new RecordItemIndex(20));
            repo.LBL0050000BTrue3DT3DViewerUs.Edit.PressKeys("{NumPad1}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot5' with region {X=162,Y=97,Width=427,Height=123}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(21));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot5, AVLAVView_Screenshot5_Options);
            Delay.Milliseconds(100);
            
            // C.11 VTP_Labeling_UserManual_Cautions_Import_Surface / Hazard(s) A3.15
            Report.Log(ReportLevel.Info, "User", "C.11 VTP_Labeling_UserManual_Cautions_Import_Surface / Hazard(s) A3.15", new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot5' with region {X=161,Y=589,Width=442,Height=98}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(23));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot5_2, AVLAVView_Screenshot5_2_Options);
            Delay.Milliseconds(100);
            
            // C.15 VTP_Labeling_UserManual_Cautions_UseRecommended / Hazard(s): A3.12
            Report.Log(ReportLevel.Info, "User", "C.15 VTP_Labeling_UserManual_Cautions_UseRecommended / Hazard(s): A3.12", new RecordItemIndex(24));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(160, 98, 440, 64)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;160,98,440,64;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_2
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(162, 168, 440, 65)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;162,168,440,65;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_3
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(157, 236, 430, 36)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_3_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;157,236,430,36;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_4
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(159, 495, 445, 51)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_4_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;159,495,445,51;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_5
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(160, 551, 426, 38)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_5_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;160,551,426,38;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_6
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(160, 591, 434, 48)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_6_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;160,591,434,48;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot4_7
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot4(new Rectangle(159, 762, 437, 68)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot4_7_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;159,762,437,68;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot5
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot5(new Rectangle(162, 97, 427, 123)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot5_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;162,97,427,123;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot5_2
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot5(new Rectangle(161, 589, 442, 98)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot5_2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;161,589,442,98;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
