///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0011_UserManual
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IDs recording.
    /// </summary>
    [TestModule("a0ae1340-3c67-465b-a789-8698ccf377b6", ModuleType.Recording, 1)]
    public partial class IDs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0011_UserManualRepository repository.
        /// </summary>
        public static TPX_0011_UserManualRepository repo = TPX_0011_UserManualRepository.Instance;

        static IDs instance = new IDs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IDs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IDs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Confirm the User Manual version and identification details
            Report.Log(ReportLevel.Info, "User", "Confirm the User Manual version and identification details", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView' at 728;453.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(1));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView.Click("728;453");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView1' at 974;720.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1Info, new RecordItemIndex(2));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1.Click("974;720");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{Return}' with focus on 'LBL0050000BTrue3DT3DViewerUs'.", repo.LBL0050000BTrue3DT3DViewerUs.SelfInfo, new RecordItemIndex(3));
            repo.LBL0050000BTrue3DT3DViewerUs.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}{Return}");
            Delay.Milliseconds(0);
            
            // Software Version
            Report.Log(ReportLevel.Info, "User", "Software Version", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=432,Y=536,Width=261,Height=57}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(5));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot1, AVLAVView_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Version
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Version", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=229,Y=888,Width=104,Height=21}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(7));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot1_2, AVLAVView_Screenshot1_2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Version
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Version", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView' at 741;678.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(9));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView.Click("741;678");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView1' at 981;721.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1Info, new RecordItemIndex(10));
            repo.LBL0050000BTrue3DT3DViewerUs.AVLAVView1.Click("981;721");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{Return}' with focus on 'LBL0050000BTrue3DT3DViewerUs'.", repo.LBL0050000BTrue3DT3DViewerUs.SelfInfo, new RecordItemIndex(11));
            repo.LBL0050000BTrue3DT3DViewerUs.Self.EnsureVisible();
            Keyboard.Press("{NumPad2}{Return}");
            Delay.Milliseconds(0);
            
            // Manufacturer
            Report.Log(ReportLevel.Info, "User", "Manufacturer", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=156,Y=128,Width=65,Height=59}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(13));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2, AVLAVView_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Manufacturer
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Manufacturer", new RecordItemIndex(14));
            
            // Address
            Report.Log(ReportLevel.Info, "User", "Address", new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=249,Y=126,Width=128,Height=63}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(16));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_2, AVLAVView_Screenshot2_2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Address
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Address", new RecordItemIndex(17));
            
            // Country of Manufacture
            Report.Log(ReportLevel.Info, "User", "Country of Manufacture", new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=155,Y=199,Width=67,Height=61}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(19));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_3, AVLAVView_Screenshot2_3_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_ConutryOfManufacture
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_ConutryOfManufacture", new RecordItemIndex(20));
            
            // Medical Device
            Report.Log(ReportLevel.Info, "User", "Medical Device", new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=286,Y=213,Width=52,Height=36}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(22));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_4, AVLAVView_Screenshot2_4_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_MD
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_MD", new RecordItemIndex(23));
            
            // UDI
            Report.Log(ReportLevel.Info, "User", "UDI", new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=390,Y=209,Width=333,Height=42}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(25));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_5, AVLAVView_Screenshot2_5_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_UDI
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_UDI", new RecordItemIndex(26));
            
            // Part Number
            Report.Log(ReportLevel.Info, "User", "Part Number", new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=387,Y=139,Width=271,Height=40}) on item 'LBL0050000BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(28));
            Validate.CompareImage(repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_6, AVLAVView_Screenshot2_6_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_PartNum
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_PartNum", new RecordItemIndex(29));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot1
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot1(new Rectangle(432, 536, 261, 57)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;432,536,261,57;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot1_2
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot1(new Rectangle(229, 888, 104, 21)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;229,888,104,21;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(156, 128, 65, 59)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;156,128,65,59;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_2
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(249, 126, 128, 63)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;249,126,128,63;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_3
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(155, 199, 67, 61)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_3_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;155,199,67,61;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_4
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(286, 213, 52, 36)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_4_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;286,213,52,36;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_5
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(390, 209, 333, 42)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_5_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;390,209,333,42;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_6
        { get { return repo.LBL0050000BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(387, 139, 271, 40)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_6_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;387,139,271,40;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
