///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0002_HW_Reqs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GPUmem recording.
    /// </summary>
    [TestModule("3c436b4b-c037-4a56-a852-fc06165f0847", ModuleType.Recording, 1)]
    public partial class GPUmem : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0002_HW_ReqsRepository repository.
        /// </summary>
        public static TPX_0002_HW_ReqsRepository repo = TPX_0002_HW_ReqsRepository.Instance;

        static GPUmem instance = new GPUmem();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GPUmem()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GPUmem Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "HDS_GPU_Min_GPU_Memory", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "The GPU must be have at least 4GB of Video Ram", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Dedicated GPU memory usage') on item 'TaskManager.GpuMemUsageTitle'.", repo.TaskManager.GpuMemUsageTitleInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.TaskManager.GpuMemUsageTitleInfo, "Text", "Dedicated GPU memory usage");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='6.0 GB') on item 'TaskManager.GpuMemoryMax'.", repo.TaskManager.GpuMemoryMaxInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.TaskManager.GpuMemoryMaxInfo, "Text", "6.0 GB");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "HDS_GPU_Min_GPU_Memory", new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
