///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0002_HW_Reqs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GPUmin recording.
    /// </summary>
    [TestModule("08d2fbfe-57a7-4ef1-82cd-71dda7adebc8", ModuleType.Recording, 1)]
    public partial class GPUmin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0002_HW_ReqsRepository repository.
        /// </summary>
        public static TPX_0002_HW_ReqsRepository repo = TPX_0002_HW_ReqsRepository.Instance;

        static GPUmin instance = new GPUmin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GPUmin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GPUmin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "HDS_GPU_Min_GPU", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "The Computer must include a Graphics Processing Unit (GPU).", new RecordItemIndex(1));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TaskManager.PerformancetabGraphs.SidebarGpuName' at 20;12.", repo.TaskManager.PerformancetabGraphs.SidebarGpuNameInfo, new RecordItemIndex(2));
            //repo.TaskManager.PerformancetabGraphs.SidebarGpuName.Click("20;12");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TaskManager.GpuEntry00707163' at 129;47.", repo.TaskManager.GpuEntry00707163Info, new RecordItemIndex(3));
            //repo.TaskManager.GpuEntry00707163.Click("129;47");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='GPU') on item 'TaskManager.ResourceTitle'.", repo.TaskManager.ResourceTitleInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.TaskManager.ResourceTitleInfo, "Text", "GPU");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "HDS_GPU_Min_GPU", new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
