///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0008_LocalPatientBrowserData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartDataG recording.
    /// </summary>
    [TestModule("3d0b59fc-327c-4b34-bbd6-4b65673d85e6", ModuleType.Recording, 1)]
    public partial class StartDataG : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0008_LocalPatientBrowserDataRepository repository.
        /// </summary>
        public static TPX_0008_LocalPatientBrowserDataRepository repo = TPX_0008_LocalPatientBrowserDataRepository.Instance;

        static StartDataG instance = new StartDataG();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartDataG()
        {
            DataGProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartDataG Instance
        {
            get { return instance; }
        }

#region Variables

        string _DataGProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable DataGProcessIDVar.
        /// </summary>
        [TestVariable("86379c82-0c79-4506-b295-7aab1bf531ca")]
        public string DataGProcessIDVar
        {
            get { return _DataGProcessIDVar; }
            set { _DataGProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"' with arguments '\"C:\\epxData\\InputDirectory\\ClientSort\\Data_G\"' in normal mode. Return value bound to $DataGProcessIDVar.", new RecordItemIndex(0));
            DataGProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"", "\"C:\\epxData\\InputDirectory\\ClientSort\\Data_G\"", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser' at 303;0.", repo.DicomBrowser.SelfInfo, new RecordItemIndex(1));
            repo.DicomBrowser.Self.DoubleClick("303;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Start DICOMBrowser.exe", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", "Open Local_Client_Sort_Data_G", new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
