///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0008_LocalPatientBrowserData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartLasMoP recording.
    /// </summary>
    [TestModule("bdff4b2d-1ae0-422b-9df1-59438b4ff08a", ModuleType.Recording, 1)]
    public partial class StartLasMoP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0008_LocalPatientBrowserDataRepository repository.
        /// </summary>
        public static TPX_0008_LocalPatientBrowserDataRepository repo = TPX_0008_LocalPatientBrowserDataRepository.Instance;

        static StartLasMoP instance = new StartLasMoP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartLasMoP()
        {
            LastMoPProcessID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartLasMoP Instance
        {
            get { return instance; }
        }

#region Variables

        string _LastMoPProcessID;

        /// <summary>
        /// Gets or sets the value of variable LastMoPProcessID.
        /// </summary>
        [TestVariable("95ff2ca9-f03e-4f4c-a9f6-f7852366cf98")]
        public string LastMoPProcessID
        {
            get { return _LastMoPProcessID; }
            set { _LastMoPProcessID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"' with arguments '\"C:\\epxData\\InputDirectory\\Ranges\\Data_LastMonthPlus\"' in normal mode. Return value bound to $LastMoPProcessID.", new RecordItemIndex(0));
            LastMoPProcessID = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"", "\"C:\\epxData\\InputDirectory\\Ranges\\Data_LastMonthPlus\"", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser' at 303;0.", repo.DicomBrowser.SelfInfo, new RecordItemIndex(1));
            repo.DicomBrowser.Self.DoubleClick("303;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Start DICOMBrowser.exe", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", "Open Local_Client_Range_Data_LastMonthPlus", new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
