///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0008_LocalPatientBrowserData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TwoWeeks recording.
    /// </summary>
    [TestModule("ebcc8475-6d2c-4400-bff4-4a030af59428", ModuleType.Recording, 1)]
    public partial class TwoWeeks : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0008_LocalPatientBrowserDataRepository repository.
        /// </summary>
        public static TPX_0008_LocalPatientBrowserDataRepository repo = TPX_0008_LocalPatientBrowserDataRepository.Instance;

        static TwoWeeks instance = new TwoWeeks();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TwoWeeks()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TwoWeeks Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Local_Client_Range_Data_2WeeksAgo", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "Test Patient Name, Patient ID, Age, Gender, Accession Num, Study Description, Referring Physician and Number of Files", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientData2WeeksAgo1' at 96;9.", repo.DicomBrowser.PatientData2WeeksAgo1Info, new RecordItemIndex(2));
            repo.DicomBrowser.PatientData2WeeksAgo1.Click("96;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row35.Cell00100010'.", repo.DicomBrowser.Row35.Cell00100010Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row35.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row35.PatientsName'.", repo.DicomBrowser.Row35.PatientsNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row35.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_2WeeksAgo') on item 'DicomBrowser.Row35.Data2WeeksAgo'.", repo.DicomBrowser.Row35.Data2WeeksAgoInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row35.Data2WeeksAgoInfo, "Text", "Data_2WeeksAgo");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0020)') on item 'DicomBrowser.Row36.Cell00100020'.", repo.DicomBrowser.Row36.Cell00100020Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row36.Cell00100020Info, "Text", "(0010,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient ID') on item 'DicomBrowser.Row36.PatientID'.", repo.DicomBrowser.Row36.PatientIDInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row36.PatientIDInfo, "Text", "Patient ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_2WeeksAgo') on item 'DicomBrowser.Row36.Data2WeeksAgo'.", repo.DicomBrowser.Row36.Data2WeeksAgoInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row36.Data2WeeksAgoInfo, "Text", "Data_2WeeksAgo");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,1010)') on item 'DicomBrowser.Row40.Cell00101010'.", repo.DicomBrowser.Row40.Cell00101010Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row40.Cell00101010Info, "Text", "(0010,1010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Age') on item 'DicomBrowser.Row40.PatientsAge'.", repo.DicomBrowser.Row40.PatientsAgeInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row40.PatientsAgeInfo, "Text", "Patient’s Age");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='066Y') on item 'DicomBrowser.Row40.Cell066Y'.", repo.DicomBrowser.Row40.Cell066YInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.DicomBrowser.Row40.Cell066YInfo, "Text", "066Y");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0040)') on item 'DicomBrowser.Row38.Cell00100040'.", repo.DicomBrowser.Row38.Cell00100040Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.DicomBrowser.Row38.Cell00100040Info, "Text", "(0010,0040)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Sex') on item 'DicomBrowser.Row38.PatientsSex'.", repo.DicomBrowser.Row38.PatientsSexInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.DicomBrowser.Row38.PatientsSexInfo, "Text", "Patient’s Sex");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='M') on item 'DicomBrowser.Row38.CellM'.", repo.DicomBrowser.Row38.CellMInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.DicomBrowser.Row38.CellMInfo, "Text", "M");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0050)') on item 'DicomBrowser.Row14.Cell00080050'.", repo.DicomBrowser.Row14.Cell00080050Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.DicomBrowser.Row14.Cell00080050Info, "Text", "(0008,0050)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Accession Number') on item 'DicomBrowser.Row14.AccessionNumber'.", repo.DicomBrowser.Row14.AccessionNumberInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.DicomBrowser.Row14.AccessionNumberInfo, "Text", "Accession Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='33445566') on item 'DicomBrowser.Row14.SomeCell'.", repo.DicomBrowser.Row14.SomeCellInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.DicomBrowser.Row14.SomeCellInfo, "Text", "33445566");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,1030)') on item 'DicomBrowser.Row20.Cell00081030'.", repo.DicomBrowser.Row20.Cell00081030Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.Cell00081030Info, "Text", "(0008,1030)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study Description') on item 'DicomBrowser.Row20.StudyDescription'.", repo.DicomBrowser.Row20.StudyDescriptionInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.StudyDescriptionInfo, "Text", "Study Description");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Brain') on item 'DicomBrowser.Row20.Brain'.", repo.DicomBrowser.Row20.BrainInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DicomBrowser.Row20.BrainInfo, "Text", "Brain");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0090)') on item 'DicomBrowser.Row18.Cell00080090'.", repo.DicomBrowser.Row18.Cell00080090Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.DicomBrowser.Row18.Cell00080090Info, "Text", "(0008,0090)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Referring Physician’s Name') on item 'DicomBrowser.Row18.ReferringPhysiciansName'.", repo.DicomBrowser.Row18.ReferringPhysiciansNameInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.DicomBrowser.Row18.ReferringPhysiciansNameInfo, "Text", "Referring Physician’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Doogie Howser') on item 'DicomBrowser.Row18.DoogieHowser'.", repo.DicomBrowser.Row18.DoogieHowserInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.DicomBrowser.Row18.DoogieHowserInfo, "Text", "Doogie Howser");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0018)') on item 'DicomBrowser.Row5.Cell00080018'.", repo.DicomBrowser.Row5.Cell00080018Info, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.Cell00080018Info, "Text", "(0008,0018)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SOP Instance UID') on item 'DicomBrowser.Row5.SOPInstanceUID'.", repo.DicomBrowser.Row5.SOPInstanceUIDInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.SOPInstanceUIDInfo, "Text", "SOP Instance UID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='10 values: 1.2.840.113619.2.80.36605742.24143.1338595321.137, 1.2.840.113619.2.80.36605742.24143.1338595321.138, 1.2.840.113619.2.80.36605742.24143.1338595321.139, 1.2.840.113619.2.80.36605742.24143.1338595321.140...') on item 'DicomBrowser.Row5.Cell10Values1284011361928036605'.", repo.DicomBrowser.Row5.Cell10Values1284011361928036605Info, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.DicomBrowser.Row5.Cell10Values1284011361928036605Info, "Text", "10 values: 1.2.840.113619.2.80.36605742.24143.1338595321.137, 1.2.840.113619.2.80.36605742.24143.1338595321.138, 1.2.840.113619.2.80.36605742.24143.1338595321.139, 1.2.840.113619.2.80.36605742.24143.1338595321.140...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "Local_Client_Range_Data_2WeeksAgo", new RecordItemIndex(27));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
