///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0026_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("19f27fd4-44df-4e9b-b789-9458c7613291", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0026_SystemRepository repository.
        /// </summary>
        public static TPX_0026_SystemRepository repo = TPX_0026_SystemRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "SYST_LOGIN", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.EpxLoginDialogPrimaryFrameUsernameLine' at Center.", repo.Login.EpxLoginDialogPrimaryFrameUsernameLineInfo, new RecordItemIndex(1));
            repo.Login.EpxLoginDialogPrimaryFrameUsernameLine.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'Login.EpxLoginDialogPrimaryFrameUsernameLine'.", repo.Login.EpxLoginDialogPrimaryFrameUsernameLineInfo, new RecordItemIndex(2));
            repo.Login.EpxLoginDialogPrimaryFrameUsernameLine.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.EpxLoginDialogPrimaryFramePasswordLine' at Center.", repo.Login.EpxLoginDialogPrimaryFramePasswordLineInfo, new RecordItemIndex(3));
            repo.Login.EpxLoginDialogPrimaryFramePasswordLine.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'Login.EpxLoginDialogPrimaryFramePasswordLine'.", repo.Login.EpxLoginDialogPrimaryFramePasswordLineInfo, new RecordItemIndex(4));
            repo.Login.EpxLoginDialogPrimaryFramePasswordLine.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.ButtonOK' at Center.", repo.Login.ButtonOKInfo, new RecordItemIndex(5));
            repo.Login.ButtonOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(7));
            Validate.NotExists(repo.Login.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "SYST_LOGIN", new RecordItemIndex(8));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
