///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0026_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginWindow recording.
    /// </summary>
    [TestModule("b064f9d3-073f-478f-927b-0cdc6fe366e7", ModuleType.Recording, 1)]
    public partial class LoginWindow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0026_SystemRepository repository.
        /// </summary>
        public static TPX_0026_SystemRepository repo = TPX_0026_SystemRepository.Instance;

        static LoginWindow instance = new LoginWindow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginWindow()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginWindow Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "SYST_MIN_LOGIN_WINDOW", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(1));
            Validate.Exists(repo.Login.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.EpxLoginDialogPrimaryFrame' at UpperCenter.", repo.Login.EpxLoginDialogPrimaryFrameInfo, new RecordItemIndex(2));
            repo.Login.EpxLoginDialogPrimaryFrame.Click(Location.UpperCenter);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=561,Height=180}) on item 'Login.EpxLoginDialogPrimaryFrameLogoLabel'.", repo.Login.EpxLoginDialogPrimaryFrameLogoLabelInfo, new RecordItemIndex(3));
            Validate.CompareImage(repo.Login.EpxLoginDialogPrimaryFrameLogoLabelInfo, EpxLoginDialogPrimaryFrameLogoLabel_Screenshot1, EpxLoginDialogPrimaryFrameLogoLabel_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Username') on item 'Login.EpxLoginDialogPrimaryFrameNewUsernameL'.", repo.Login.EpxLoginDialogPrimaryFrameNewUsernameLInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Login.EpxLoginDialogPrimaryFrameNewUsernameLInfo, "Text", "Username");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Password') on item 'Login.EpxLoginDialogPrimaryFrameNewPasswordL'.", repo.Login.EpxLoginDialogPrimaryFrameNewPasswordLInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.Login.EpxLoginDialogPrimaryFrameNewPasswordLInfo, "Text", "Password");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='OK') on item 'Login.ButtonOK'.", repo.Login.ButtonOKInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.Login.ButtonOKInfo, "Text", "OK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cancel') on item 'Login.Cancel'.", repo.Login.CancelInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.Login.CancelInfo, "Text", "Cancel");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='THIS IS UNVERIFIED CODE, PROVIDED FOR USER FEEDBACK.\nTHIS PRODUCT SHOULD NOT BE USED FOR HUMAN CLINICAL PURPOSES!') on item 'Login.EpxLoginDialogPrimaryFrameUnverifiedCo'.", repo.Login.EpxLoginDialogPrimaryFrameUnverifiedCoInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.Login.EpxLoginDialogPrimaryFrameUnverifiedCoInfo, "Text", "THIS IS UNVERIFIED CODE, PROVIDED FOR USER FEEDBACK.\nTHIS PRODUCT SHOULD NOT BE USED FOR HUMAN CLINICAL PURPOSES!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "SYST_MIN_LOGIN_WINDOW", new RecordItemIndex(9));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage EpxLoginDialogPrimaryFrameLogoLabel_Screenshot1
        { get { return repo.Login.EpxLoginDialogPrimaryFrameLogoLabelInfo.GetScreenshot1(new Rectangle(0, 0, 561, 180)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions EpxLoginDialogPrimaryFrameLogoLabel_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;0,0,561,180;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
