///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0026_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginUID recording.
    /// </summary>
    [TestModule("9e847b23-1fa6-4910-9374-f4cb23930753", ModuleType.Recording, 1)]
    public partial class LoginUID : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0026_SystemRepository repository.
        /// </summary>
        public static TPX_0026_SystemRepository repo = TPX_0026_SystemRepository.Instance;

        static LoginUID instance = new LoginUID();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginUID()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginUID Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "SYST_MIN_LOGIN_UID", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='UDI: (01)00851325007003(10)0.0.0.4613.465 - Develop - origin: 1.7.2') on item 'Login.EpxLoginDialogPrimaryFrameSoftwareUDI'.", repo.Login.EpxLoginDialogPrimaryFrameSoftwareUDIInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.Login.EpxLoginDialogPrimaryFrameSoftwareUDIInfo, "Text", "UDI: (01)00851325007003(10)0.0.0.4613.465 - Develop - origin: 1.7.2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "SYST_MIN_LOGIN_UID", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
