///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0026_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ray recording.
    /// </summary>
    [TestModule("c5c5fb99-1ada-4b01-aa16-ece7c57d70b7", ModuleType.Recording, 1)]
    public partial class ray : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0026_SystemRepository repository.
        /// </summary>
        public static TPX_0026_SystemRepository repo = TPX_0026_SystemRepository.Instance;

        static ray instance = new ray();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ray()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ray Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "SYST_MIN_RAY", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'R' Press with focus on 'True3DViewer'.", repo.True3DViewer.SelfInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.True3DViewer.Self);
            Keyboard.Press(System.Windows.Forms.Keys.R, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'True3DViewer.Reporting' at Center.", repo.True3DViewer.ReportingInfo, new RecordItemIndex(2));
            repo.True3DViewer.Reporting.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'True3DViewer.Reporting' at 59;102.", repo.True3DViewer.ReportingInfo, new RecordItemIndex(3));
            repo.True3DViewer.Reporting.Click("59;102");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions' at 476;44.", repo.RecordPlaybackActions.SelfInfo, new RecordItemIndex(4));
            repo.RecordPlaybackActions.Self.Click("476;44");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions' at 571;99.", repo.RecordPlaybackActions.SelfInfo, new RecordItemIndex(5));
            repo.RecordPlaybackActions.Self.Click("571;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoadSaveCommandScriptWithName' at 385;33.", repo.LoadSaveCommandScriptWithName.SelfInfo, new RecordItemIndex(6));
            repo.LoadSaveCommandScriptWithName.Self.Click("385;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoadSaveCommandScriptWithName' at 173;393.", repo.LoadSaveCommandScriptWithName.SelfInfo, new RecordItemIndex(7));
            repo.LoadSaveCommandScriptWithName.Self.Click("173;393");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}C{LShiftKey down}:\\{LShiftKey down}Users\\'.", new RecordItemIndex(8));
            Keyboard.Press("{LShiftKey down}C{LShiftKey down}:\\{LShiftKey down}Users\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't3{LShiftKey down}D\\{LShiftKey down}Desktop\\test{LShiftKey down}_data\\'.", new RecordItemIndex(9));
            Keyboard.Press("t3{LShiftKey down}D\\{LShiftKey down}Desktop\\test{LShiftKey down}_data\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey down}P{LShiftKey down}X-{NumPad0}{NumPad0}{NumPad2}{NumPad6}{LShiftKey down}_stylus.xml'.", new RecordItemIndex(10));
            Keyboard.Press("{LShiftKey down}T{LShiftKey down}P{LShiftKey down}X-{NumPad0}{NumPad0}{NumPad2}{NumPad6}{LShiftKey down}_stylus.xml");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoadSaveCommandScriptWithName.Open' at 21;13.", repo.LoadSaveCommandScriptWithName.OpenInfo, new RecordItemIndex(11));
            repo.LoadSaveCommandScriptWithName.Open.Click("21;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions' at 234;135.", repo.RecordPlaybackActions.SelfInfo, new RecordItemIndex(12));
            repo.RecordPlaybackActions.Self.Click("234;135");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions.EpxCommandScriptDialogPlayButton' at 24;24.", repo.RecordPlaybackActions.EpxCommandScriptDialogPlayButtonInfo, new RecordItemIndex(13));
            repo.RecordPlaybackActions.EpxCommandScriptDialogPlayButton.Click("24;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(14));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions' at 212;82.", repo.RecordPlaybackActions.SelfInfo, new RecordItemIndex(15));
            repo.RecordPlaybackActions.Self.Click("212;82");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RecordPlaybackActions.TextRecordPlaybackActions' at 576;12.", repo.RecordPlaybackActions.TextRecordPlaybackActionsInfo, new RecordItemIndex(16));
            repo.RecordPlaybackActions.TextRecordPlaybackActions.Click("576;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'True3DViewer.Qt5QWindowOwnDCIcon' at 1109;184.", repo.True3DViewer.Qt5QWindowOwnDCIconInfo, new RecordItemIndex(17));
            repo.True3DViewer.Qt5QWindowOwnDCIcon.Click("1109;184");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'R' Press with focus on 'True3DViewer'.", repo.True3DViewer.SelfInfo, new RecordItemIndex(18));
            Keyboard.PrepareFocus(repo.True3DViewer.Self);
            Keyboard.Press(System.Windows.Forms.Keys.R, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "SYST_MIN_RAY", new RecordItemIndex(19));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
