///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0022_HD_MONITOR
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseLowDisk recording.
    /// </summary>
    [TestModule("25938433-4bde-46ac-bf3d-ce126a232de9", ModuleType.Recording, 1)]
    public partial class CloseLowDisk : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0022_HD_MONITORRepository repository.
        /// </summary>
        public static TPX_0022_HD_MONITORRepository repo = TPX_0022_HD_MONITORRepository.Instance;

        static CloseLowDisk instance = new CloseLowDisk();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseLowDisk()
        {
            LowDiskProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseLowDisk Instance
        {
            get { return instance; }
        }

#region Variables

        string _LowDiskProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable LowDiskProcessIDVar.
        /// </summary>
        [TestVariable("27e2e05e-9a25-4807-b525-5cf46e82b8fc")]
        public string LowDiskProcessIDVar
        {
            get { return _LowDiskProcessIDVar; }
            set { _LowDiskProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $LowDiskProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(LowDiskProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
