///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0022_HD_MONITOR
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartDelDrive recording.
    /// </summary>
    [TestModule("62eabf00-6c2c-4afd-8e98-7f881e843804", ModuleType.Recording, 1)]
    public partial class StartDelDrive : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0022_HD_MONITORRepository repository.
        /// </summary>
        public static TPX_0022_HD_MONITORRepository repo = TPX_0022_HD_MONITORRepository.Instance;

        static StartDelDrive instance = new StartDelDrive();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartDelDrive()
        {
            DelDriveProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartDelDrive Instance
        {
            get { return instance; }
        }

#region Variables

        string _DelDriveProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable DelDriveProcessIDVar.
        /// </summary>
        [TestVariable("7c2ae0d0-daf8-4fb7-9ae5-3c645b4e3129")]
        public string DelDriveProcessIDVar
        {
            get { return _DelDriveProcessIDVar; }
            set { _DelDriveProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(0));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files\\Echopixel\\True3DViewer\\bin\\epxConfigApp.exe' in normal mode. Return value bound to $DelDriveProcessIDVar.", new RecordItemIndex(1));
            DelDriveProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("C:\\Program Files\\Echopixel\\True3DViewer\\bin\\epxConfigApp.exe", "", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginWindow' at 459;201.", repo.LoginWindow.SelfInfo, new RecordItemIndex(2));
            repo.LoginWindow.Self.Click("459;201");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginWindow.UsernameTb' at 30;8.", repo.LoginWindow.UsernameTbInfo, new RecordItemIndex(3));
            repo.LoginWindow.UsernameTb.Click("30;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'root' with focus on 'LoginWindow.UsernameTb'.", repo.LoginWindow.UsernameTbInfo, new RecordItemIndex(4));
            repo.LoginWindow.UsernameTb.PressKeys("root");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginWindow.KeypssTb' at 28;6.", repo.LoginWindow.KeypssTbInfo, new RecordItemIndex(5));
            repo.LoginWindow.KeypssTb.Click("28;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'LoginWindow.KeypssTb'.", repo.LoginWindow.KeypssTbInfo, new RecordItemIndex(6));
            repo.LoginWindow.KeypssTb.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginWindow.LoginBtn' at 24;14.", repo.LoginWindow.LoginBtnInfo, new RecordItemIndex(7));
            repo.LoginWindow.LoginBtn.Click("24;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.DataDrive' at 25;7.", repo.ConfigurationApplication.DataDriveInfo, new RecordItemIndex(8));
            repo.ConfigurationApplication.DataDrive.Click("25;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
