///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0016_DICOM_Config
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoteDelete recording.
    /// </summary>
    [TestModule("bfb330aa-f8ca-4f6a-bacb-77b5a9948baf", ModuleType.Recording, 1)]
    public partial class RemoteDelete : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0016_DICOM_ConfigRepository repository.
        /// </summary>
        public static TPX_0016_DICOM_ConfigRepository repo = TPX_0016_DICOM_ConfigRepository.Instance;

        static RemoteDelete instance = new RemoteDelete();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoteDelete()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoteDelete Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_CONFIG_REMOTE_DELETE", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", "Delete Remote AE ORTHANC & DVTK PACS", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.TabControl' at 498;113.", repo.ConfigurationApplication.TabControlInfo, new RecordItemIndex(2));
            repo.ConfigurationApplication.TabControl.Click("498;113");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.RemoteAE' at 44;9.", repo.ConfigurationApplication.RemoteAEInfo, new RecordItemIndex(3));
            repo.ConfigurationApplication.RemoteAE.Click("44;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.TabControl' at 621;145.", repo.ConfigurationApplication.TabControlInfo, new RecordItemIndex(4));
            repo.ConfigurationApplication.TabControl.Click("621;145");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.RemoteEditBtn' at 57;10.", repo.ConfigurationApplication.RemoteEditBtnInfo, new RecordItemIndex(5));
            repo.ConfigurationApplication.RemoteEditBtn.Click("57;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.RemotedeleteBtn' at 67;9.", repo.ConfigurationApplication.RemotedeleteBtnInfo, new RecordItemIndex(6));
            repo.ConfigurationApplication.RemotedeleteBtn.Click("67;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Remote AE List:') on item 'ConfigurationApplication.RemoteAETListLabel'.", repo.ConfigurationApplication.RemoteAETListLabelInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ConfigurationApplication.RemoteAETListLabelInfo, "Text", "Remote AE List:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ConfigurationApplication.SomeText1'.", repo.ConfigurationApplication.SomeText1Info, new RecordItemIndex(8));
            Validate.Exists(repo.ConfigurationApplication.SomeText1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "DCM_CONFIG_REMOTE_DELETE", new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
