///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0019_DCM_QR
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Qid recording.
    /// </summary>
    [TestModule("36a0e536-0a9b-4b60-8079-831c5e008580", ModuleType.Recording, 1)]
    public partial class Qid : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0019_DCM_QRRepository repository.
        /// </summary>
        public static TPX_0019_DCM_QRRepository repo = TPX_0019_DCM_QRRepository.Instance;

        static Qid instance = new Qid();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Qid()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Qid Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_CMD_QUERY_ID", new RecordItemIndex(0));
            
            // Select Remote Server - Orthanc
            Report.Log(ReportLevel.Info, "Section", "Select Remote Server - Orthanc", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.ParentWindowGridView' at 1429;63.", repo.PatientBrowser.ParentWindowGridViewInfo, new RecordItemIndex(2));
            repo.PatientBrowser.ParentWindowGridView.Click("1429;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.ToggleButton' at 192;6.", repo.PatientBrowser.ToggleButtonInfo, new RecordItemIndex(3));
            repo.PatientBrowser.ToggleButton.Click("192;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Select source - Remote Server ORTHANC", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EpxPatientBrowser.ORTHANCPACS1' at 146;6.", repo.EpxPatientBrowser.ORTHANCPACS1Info, new RecordItemIndex(5));
            repo.EpxPatientBrowser.ORTHANCPACS1.Click("146;6");
            Delay.Milliseconds(0);
            
            // Input Query Parameters
            Report.Log(ReportLevel.Info, "Section", "Input Query Parameters", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "User", "Trigger QUERY: Modality field = ALL, ID = S8", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.PatientIdTb' at 147;7.", repo.PatientBrowser.PatientIdTbInfo, new RecordItemIndex(8));
            repo.PatientBrowser.PatientIdTb.Click("147;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'S{Capital}{NumPad8}'.", new RecordItemIndex(9));
            Keyboard.Press("S{Capital}{NumPad8}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.SearchBtn' at 82;10.", repo.PatientBrowser.SearchBtnInfo, new RecordItemIndex(10));
            repo.PatientBrowser.SearchBtn.Click("82;10");
            Delay.Milliseconds(0);
            
            // Validate
            Report.Log(ReportLevel.Info, "Section", "Validate", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=1334,Height=519}) on item 'PatientBrowser.PatientListview'.", repo.PatientBrowser.PatientListviewInfo, new RecordItemIndex(12));
            Validate.CompareImage(repo.PatientBrowser.PatientListviewInfo, PatientListview_Screenshot3, PatientListview_Screenshot3_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=1322,Height=15}) on item 'PatientBrowser.PatientListview1.SomeContainer'.", repo.PatientBrowser.PatientListview1.SomeContainerInfo, new RecordItemIndex(13));
            Validate.CompareImage(repo.PatientBrowser.PatientListview1.SomeContainerInfo, SomeContainer_Screenshot1, SomeContainer_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_S8 ') on item 'PatientBrowser.PatientListview1.DataS8'.", repo.PatientBrowser.PatientListview1.DataS8Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview1.DataS8Info, "Text", "Data_S8 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='S8') on item 'PatientBrowser.PatientListview1.TextS8'.", repo.PatientBrowser.PatientListview1.TextS8Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview1.TextS8Info, "Text", "S8");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='052Y') on item 'PatientBrowser.PatientListview1.Text052Y2'.", repo.PatientBrowser.PatientListview1.Text052Y2Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview1.Text052Y2Info, "Text", "052Y");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='M') on item 'PatientBrowser.PatientListview1.TextM2'.", repo.PatientBrowser.PatientListview1.TextM2Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview1.TextM2Info, "Text", "M");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='ORTHANCPACS') on item 'PatientBrowser.PatientListview1.ORTHANCPACS4'.", repo.PatientBrowser.PatientListview1.ORTHANCPACS4Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview1.ORTHANCPACS4Info, "Text", "ORTHANCPACS");
            Delay.Milliseconds(100);
            
            // Clean Up
            Report.Log(ReportLevel.Info, "Section", "Clean Up", new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.ParentWindowGridView' at 1767;155.", repo.PatientBrowser.ParentWindowGridViewInfo, new RecordItemIndex(20));
            repo.PatientBrowser.ParentWindowGridView.Click("1767;155");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.ToggleButton' at 193;11.", repo.PatientBrowser.ToggleButtonInfo, new RecordItemIndex(21));
            repo.PatientBrowser.ToggleButton.Click("193;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EpxPatientBrowser.LOCAL' at 170;5.", repo.EpxPatientBrowser.LOCALInfo, new RecordItemIndex(22));
            repo.EpxPatientBrowser.LOCAL.Click("170;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.SomeButton' at 56;39.", repo.PatientBrowser.SomeButtonInfo, new RecordItemIndex(23));
            repo.PatientBrowser.SomeButton.Click("56;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "DCM_CMD_QUERY_ID", new RecordItemIndex(24));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage PatientListview_Screenshot3
        { get { return repo.PatientBrowser.PatientListviewInfo.GetScreenshot3(new Rectangle(0, 0, 1334, 519)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions PatientListview_Screenshot3_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;0,0,1334,519;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage SomeContainer_Screenshot1
        { get { return repo.PatientBrowser.PatientListview1.SomeContainerInfo.GetScreenshot1(new Rectangle(0, 0, 1322, 15)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions SomeContainer_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;0,0,1322,15;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
