///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0012_LBL_0004
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Prep recording.
    /// </summary>
    [TestModule("3245ec0b-5d9e-4dcf-93a7-1b8ef511f331", ModuleType.Recording, 1)]
    public partial class Prep : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0012_LBL_0004Repository repository.
        /// </summary>
        public static TPX_0012_LBL_0004Repository repo = TPX_0012_LBL_0004Repository.Instance;

        static Prep instance = new Prep();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Prep()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Prep Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // LBL-0004 Prep test start
            Report.Log(ReportLevel.Info, "User", "LBL-0004 Prep test start", new RecordItemIndex(0));
            
            // Position label - finished product view
            Report.Log(ReportLevel.Info, "User", "Position label - finished product view", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.AVLAVView' at 25;14.", repo.AdobeAcrobatReader64Bit.AVLAVViewInfo, new RecordItemIndex(2));
            repo.AdobeAcrobatReader64Bit.AVLAVView.Click("25;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.AVLAVView1' at 46;19.", repo.AdobeAcrobatReader64Bit.AVLAVView1Info, new RecordItemIndex(3));
            repo.AdobeAcrobatReader64Bit.AVLAVView1.Click("46;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Acrobat.OpenCtrlPlusO' at 35;19.", repo.Acrobat.OpenCtrlPlusOInfo, new RecordItemIndex(4));
            repo.Acrobat.OpenCtrlPlusO.Click("35;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.Desktop' at 5;12.", repo.Open.DesktopInfo, new RecordItemIndex(5));
            repo.Open.Desktop.Click("5;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ListItem2' at 44;65.", repo.Open.ListItem2Info, new RecordItemIndex(6));
            repo.Open.ListItem2.Click("44;65");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 34;15.", repo.Open.ButtonOpenInfo, new RecordItemIndex(7));
            repo.Open.ButtonOpen.Click("34;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.SystemItemNameDisplay' at 179;7.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(8));
            repo.Open.SystemItemNameDisplay.Click("179;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 24;8.", repo.Open.ButtonOpenInfo, new RecordItemIndex(9));
            repo.Open.ButtonOpen.Click("24;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.AVLAVView2' at 264;72.", repo.AdobeAcrobatReader64Bit.AVLAVView2Info, new RecordItemIndex(10));
            repo.AdobeAcrobatReader64Bit.AVLAVView2.Click("264;72");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.AVLAVView2' at 982;938.", repo.AdobeAcrobatReader64Bit.AVLAVView2Info, new RecordItemIndex(11));
            repo.AdobeAcrobatReader64Bit.AVLAVView2.Click("982;938");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.AVLAVView2' at 982;938.", repo.AdobeAcrobatReader64Bit.AVLAVView2Info, new RecordItemIndex(12));
            repo.AdobeAcrobatReader64Bit.AVLAVView2.Click("982;938");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdobeAcrobatReader64Bit.PageDown' at 203;12.", repo.AdobeAcrobatReader64Bit.PageDownInfo, new RecordItemIndex(13));
            repo.AdobeAcrobatReader64Bit.PageDown.Click("203;12");
            Delay.Milliseconds(0);
            
            // LBL-0004 Prep test end
            Report.Log(ReportLevel.Info, "User", "LBL-0004 Prep test end", new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
