///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0023_HD_MONITOR_MISSING
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CleanUp recording.
    /// </summary>
    [TestModule("2be69b6a-47f8-49cb-bc7f-d4b7c470ebdf", ModuleType.Recording, 1)]
    public partial class CleanUp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0023_HD_MONITOR_MISSINGRepository repository.
        /// </summary>
        public static TPX_0023_HD_MONITOR_MISSINGRepository repo = TPX_0023_HD_MONITOR_MISSINGRepository.Instance;

        static CleanUp instance = new CleanUp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CleanUp()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CleanUp Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.TabControl' at 462;70.", repo.ConfigurationApplication.TabControlInfo, new RecordItemIndex(0));
            repo.ConfigurationApplication.TabControl.Click("462;70");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.ToggleButton' at 110;12.", repo.ConfigurationApplication.ToggleButtonInfo, new RecordItemIndex(1));
            repo.ConfigurationApplication.ToggleButton.Click("110;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EpxConfigApp.TextF' at 50;6.", repo.EpxConfigApp.TextFInfo, new RecordItemIndex(2));
            repo.EpxConfigApp.TextF.Click("50;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfigurationApplication.DataDrivedeleteBtn' at 42;10.", repo.ConfigurationApplication.DataDrivedeleteBtnInfo, new RecordItemIndex(3));
            repo.ConfigurationApplication.DataDrivedeleteBtn.Click("42;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'DataDriveDeleteConfirmationDialog'", repo.DataDriveDeleteConfirmationDialog.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.DataDriveDeleteConfirmationDialog.SelfInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DataDriveDeleteConfirmationDialog.DataDriveDeleteConfirmationDialog' at 108;124.", repo.DataDriveDeleteConfirmationDialog.DataDriveDeleteConfirmationDialogInfo, new RecordItemIndex(5));
            repo.DataDriveDeleteConfirmationDialog.DataDriveDeleteConfirmationDialog.Click("108;124");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DataDriveDeleteConfirmationDialog.ButtonOK' at 32;12.", repo.DataDriveDeleteConfirmationDialog.ButtonOKInfo, new RecordItemIndex(6));
            repo.DataDriveDeleteConfirmationDialog.ButtonOK.Click("32;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'MessageBox'", repo.MessageBox.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(7));
            repo.MessageBox.SelfInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessageBox' at 139;135.", repo.MessageBox.SelfInfo, new RecordItemIndex(8));
            repo.MessageBox.Self.Click("139;135");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MessageBox.ButtonOk' at 38;7.", repo.MessageBox.ButtonOkInfo, new RecordItemIndex(9));
            repo.MessageBox.ButtonOk.DoubleClick("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data Drive List:') on item 'ConfigurationApplication.DataDriveListLabel'.", repo.ConfigurationApplication.DataDriveListLabelInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ConfigurationApplication.DataDriveListLabelInfo, "Text", "Data Drive List:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='E:\\') on item 'ConfigurationApplication.TextE'.", repo.ConfigurationApplication.TextEInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ConfigurationApplication.TextEInfo, "Text", "E:\\");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
