///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0020_Import_Export
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PushStatus recording.
    /// </summary>
    [TestModule("7ea23599-b4e5-4c40-8a6d-e549131d153c", ModuleType.Recording, 1)]
    public partial class PushStatus : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0020_Import_ExportRepository repository.
        /// </summary>
        public static TPX_0020_Import_ExportRepository repo = TPX_0020_Import_ExportRepository.Instance;

        static PushStatus instance = new PushStatus();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PushStatus()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PushStatus Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_PUSH_STATUS_GR", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomPushWin.Push' at 56;8.", repo.DicomPushWin.PushInfo, new RecordItemIndex(1));
            repo.DicomPushWin.Push.Click("56;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=503,Y=0,Width=73,Height=71}) on item 'PatientBrowser.SomeContainer'.", repo.PatientBrowser.SomeContainerInfo, new RecordItemIndex(3));
            Validate.CompareImage(repo.PatientBrowser.SomeContainerInfo, SomeContainer_Screenshot2, SomeContainer_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "DCM_PUSH_STATUS_GR", new RecordItemIndex(4));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage SomeContainer_Screenshot2
        { get { return repo.PatientBrowser.SomeContainerInfo.GetScreenshot2(new Rectangle(503, 0, 73, 71)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions SomeContainer_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;503,0,73,71;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
