///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0020_Import_Export
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StatusUpdate recording.
    /// </summary>
    [TestModule("9c124817-4308-455b-86aa-9114517f71fd", ModuleType.Recording, 1)]
    public partial class StatusUpdate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0020_Import_ExportRepository repository.
        /// </summary>
        public static TPX_0020_Import_ExportRepository repo = TPX_0020_Import_ExportRepository.Instance;

        static StatusUpdate instance = new StatusUpdate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StatusUpdate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StatusUpdate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_IMPORT_STATUS_UPDATE_GR", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DICOMImportWindow.TxtImportTextBox' at 163;12.", repo.DICOMImportWindow.TxtImportTextBoxInfo, new RecordItemIndex(1));
            repo.DICOMImportWindow.TxtImportTextBox.Click("163;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{Home}{LShiftKey up}{Delete}' with focus on 'DICOMImportWindow.TxtImportTextBox'.", repo.DICOMImportWindow.TxtImportTextBoxInfo, new RecordItemIndex(2));
            repo.DICOMImportWindow.TxtImportTextBox.PressKeys("{LShiftKey down}{Home}{LShiftKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C{LShiftKey down}:{LShiftKey up}\\epxData\\InputDirectory\\Modality_tests\\TwoModalityOneSeries' with focus on 'DICOMImportWindow.TxtImportTextBox'.", repo.DICOMImportWindow.TxtImportTextBoxInfo, new RecordItemIndex(3));
            repo.DICOMImportWindow.TxtImportTextBox.PressKeys("C{LShiftKey down}:{LShiftKey up}\\epxData\\InputDirectory\\Modality_tests\\TwoModalityOneSeries");
            Delay.Milliseconds(4560);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DICOMImportWindow.ImportBtn' at 45;8.", repo.DICOMImportWindow.ImportBtnInfo, new RecordItemIndex(4));
            repo.DICOMImportWindow.ImportBtn.Click("45;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=503,Y=0,Width=73,Height=71}) on item 'PatientBrowser.SomeContainer'.", repo.PatientBrowser.SomeContainerInfo, new RecordItemIndex(6));
            Validate.CompareImage(repo.PatientBrowser.SomeContainerInfo, SomeContainer_Screenshot2, SomeContainer_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "DCM_IMPORT_STATUS_UPDATE_GR", new RecordItemIndex(7));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage SomeContainer_Screenshot2
        { get { return repo.PatientBrowser.SomeContainerInfo.GetScreenshot2(new Rectangle(503, 0, 73, 71)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions SomeContainer_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;503,0,73,71;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
