///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0020_Import_Export
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Store recording.
    /// </summary>
    [TestModule("849a7d44-23d8-4864-99ca-8b26aae3a2fc", ModuleType.Recording, 1)]
    public partial class Store : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0020_Import_ExportRepository repository.
        /// </summary>
        public static TPX_0020_Import_ExportRepository repo = TPX_0020_Import_ExportRepository.Instance;

        static Store instance = new Store();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Store()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Store Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_CMD_STORE_IMPORT", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient Name') on item 'PatientBrowser.PatientListview.PatientName'.", repo.PatientBrowser.PatientListview.PatientNameInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.PatientNameInfo, "Text", "Patient Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Acquisition Datetime Invalid ') on item 'PatientBrowser.PatientListview.AcquisitionDatetimeInvalid'.", repo.PatientBrowser.PatientListview.AcquisitionDatetimeInvalidInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.AcquisitionDatetimeInvalidInfo, "Text", "Acquisition Datetime Invalid ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_C1 ') on item 'PatientBrowser.PatientListview.DataC1'.", repo.PatientBrowser.PatientListview.DataC1Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataC1Info, "Text", "Data_C1 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_C2 ') on item 'PatientBrowser.PatientListview.DataC21'.", repo.PatientBrowser.PatientListview.DataC21Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataC21Info, "Text", "Data_C2 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_C3 ') on item 'PatientBrowser.PatientListview.DataC3'.", repo.PatientBrowser.PatientListview.DataC3Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataC3Info, "Text", "Data_C3 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_C4 ') on item 'PatientBrowser.PatientListview.DataC41'.", repo.PatientBrowser.PatientListview.DataC41Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataC41Info, "Text", "Data_C4 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_CSC ') on item 'PatientBrowser.PatientListview.DataCSC'.", repo.PatientBrowser.PatientListview.DataCSCInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataCSCInfo, "Text", "Data_CSC ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data_CScene ') on item 'PatientBrowser.PatientListview.DataCScene'.", repo.PatientBrowser.PatientListview.DataCSceneInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataCSceneInfo, "Text", "Data_CScene ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Philips_Ultrasound_3DDCM ') on item 'PatientBrowser.PatientListview.PhilipsUltrasound3DDCM3'.", repo.PatientBrowser.PatientListview.PhilipsUltrasound3DDCM3Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.PhilipsUltrasound3DDCM3Info, "Text", "Philips_Ultrasound_3DDCM ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TwoModality OneSeries ') on item 'PatientBrowser.PatientListview.TwoModalityOneSeries1'.", repo.PatientBrowser.PatientListview.TwoModalityOneSeries1Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.TwoModalityOneSeries1Info, "Text", "TwoModality OneSeries ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Data Source') on item 'PatientBrowser.PatientListview.DataSource'.", repo.PatientBrowser.PatientListview.DataSourceInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.DataSourceInfo, "Text", "Data Source");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local1'.", repo.PatientBrowser.PatientListview.Local1Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local1Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local'.", repo.PatientBrowser.PatientListview.LocalInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.LocalInfo, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local2'.", repo.PatientBrowser.PatientListview.Local2Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local2Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local3'.", repo.PatientBrowser.PatientListview.Local3Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local3Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local4'.", repo.PatientBrowser.PatientListview.Local4Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local4Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local5'.", repo.PatientBrowser.PatientListview.Local5Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local5Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local6'.", repo.PatientBrowser.PatientListview.Local6Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local6Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local7'.", repo.PatientBrowser.PatientListview.Local7Info, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local7Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Local') on item 'PatientBrowser.PatientListview.Local8'.", repo.PatientBrowser.PatientListview.Local8Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.PatientBrowser.PatientListview.Local8Info, "Text", "Local");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "DCM_CMD_STORE_IMPORT", new RecordItemIndex(21));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
