///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0020_Import_Export
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TwoMods recording.
    /// </summary>
    [TestModule("0667f9ae-560c-4b46-a00e-efe21b0e4e25", ModuleType.Recording, 1)]
    public partial class TwoMods : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0020_Import_ExportRepository repository.
        /// </summary>
        public static TPX_0020_Import_ExportRepository repo = TPX_0020_Import_ExportRepository.Instance;

        static TwoMods instance = new TwoMods();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TwoMods()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TwoMods Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "DCM_IMPORT_DATATYPES_2MODS1SERIES", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientBrowser.Status' at 16;7.", repo.PatientBrowser.StatusInfo, new RecordItemIndex(1));
            repo.PatientBrowser.Status.Click("16;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.TransferStatusWindow' at 416;16.", repo.TransferStatusWindow.TransferStatusWindowInfo, new RecordItemIndex(2));
            repo.TransferStatusWindow.TransferStatusWindow.Click("416;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.SomeContainer' at 462;23.", repo.TransferStatusWindow.SomeContainerInfo, new RecordItemIndex(3));
            repo.TransferStatusWindow.SomeContainer.Click("462;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.TransferStatusWindow' at 586;18.", repo.TransferStatusWindow.TransferStatusWindowInfo, new RecordItemIndex(4));
            repo.TransferStatusWindow.TransferStatusWindow.Click("586;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient Id') on item 'TransferStatusWindow.SomeContainer1.PatientId'.", repo.TransferStatusWindow.SomeContainer1.PatientIdInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.TransferStatusWindow.SomeContainer1.PatientIdInfo, "Text", "Patient Id");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Issue472') on item 'TransferStatusWindow.TransferLvc.Issue472'.", repo.TransferStatusWindow.TransferLvc.Issue472Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.TransferStatusWindow.TransferLvc.Issue472Info, "Text", "Issue472");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient Name') on item 'TransferStatusWindow.SomeContainer1.PatientName'.", repo.TransferStatusWindow.SomeContainer1.PatientNameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.TransferStatusWindow.SomeContainer1.PatientNameInfo, "Text", "Patient Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TwoModality OneSeries ') on item 'TransferStatusWindow.TransferLvc.TwoModalityOneSeries'.", repo.TransferStatusWindow.TransferLvc.TwoModalityOneSeriesInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.TransferStatusWindow.TransferLvc.TwoModalityOneSeriesInfo, "Text", "TwoModality OneSeries ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='# Files') on item 'TransferStatusWindow.SomeContainer1.TextHashFiles'.", repo.TransferStatusWindow.SomeContainer1.TextHashFilesInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TransferStatusWindow.SomeContainer1.TextHashFilesInfo, "Text", "# Files");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'TransferStatusWindow.TransferLvc.Text2'.", repo.TransferStatusWindow.TransferLvc.Text2Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.TransferStatusWindow.TransferLvc.Text2Info, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.Clear' at 23;11.", repo.TransferStatusWindow.ClearInfo, new RecordItemIndex(11));
            repo.TransferStatusWindow.Clear.Click("23;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.Clear1' at 27;16.", repo.TransferStatusWindow.Clear1Info, new RecordItemIndex(12));
            repo.TransferStatusWindow.Clear1.Click("27;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TransferStatusWindow.Close' at 15;12.", repo.TransferStatusWindow.CloseInfo, new RecordItemIndex(13));
            repo.TransferStatusWindow.Close.Click("15;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "DCM_IMPORT_DATATYPES_2MODS1SERIES", new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
