///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TPX_0015_BackgroundServices
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TPX_0015_BackgroundServicesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e9efb02d-afe8-4c7c-91a9-287a31ed0afa")]
    public partial class TPX_0015_BackgroundServicesRepository : RepoGenBaseFolder
    {
        static TPX_0015_BackgroundServicesRepository instance = new TPX_0015_BackgroundServicesRepository();
        TPX_0015_BackgroundServicesRepositoryFolders.ServicesAppFolder _services;
        TPX_0015_BackgroundServicesRepositoryFolders.ContextMenuMmcAppFolder _contextmenummc;
        TPX_0015_BackgroundServicesRepositoryFolders.ViewsHtmAppFolder _viewshtm;

        /// <summary>
        /// Gets the singleton class instance representing the TPX_0015_BackgroundServicesRepository element repository.
        /// </summary>
        [RepositoryFolder("e9efb02d-afe8-4c7c-91a9-287a31ed0afa")]
        public static TPX_0015_BackgroundServicesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TPX_0015_BackgroundServicesRepository() 
            : base("TPX_0015_BackgroundServicesRepository", "/", null, 0, false, "e9efb02d-afe8-4c7c-91a9-287a31ed0afa", ".\\RepositoryImages\\TPX_0015_BackgroundServicesRepositorye9efb02d.rximgres")
        {
            _services = new TPX_0015_BackgroundServicesRepositoryFolders.ServicesAppFolder(this);
            _contextmenummc = new TPX_0015_BackgroundServicesRepositoryFolders.ContextMenuMmcAppFolder(this);
            _viewshtm = new TPX_0015_BackgroundServicesRepositoryFolders.ViewsHtmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e9efb02d-afe8-4c7c-91a9-287a31ed0afa")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Services folder.
        /// </summary>
        [RepositoryFolder("6ad69b29-6ebc-4115-a2df-c041640d3308")]
        public virtual TPX_0015_BackgroundServicesRepositoryFolders.ServicesAppFolder Services
        {
            get { return _services; }
        }

        /// <summary>
        /// The ContextMenuMmc folder.
        /// </summary>
        [RepositoryFolder("542cbbcc-d08a-4d53-a2c1-bed354135c28")]
        public virtual TPX_0015_BackgroundServicesRepositoryFolders.ContextMenuMmcAppFolder ContextMenuMmc
        {
            get { return _contextmenummc; }
        }

        /// <summary>
        /// The ViewsHtm folder.
        /// </summary>
        [RepositoryFolder("efaa0d0b-23f5-41a0-98e3-45b49e869991")]
        public virtual TPX_0015_BackgroundServicesRepositoryFolders.ViewsHtmAppFolder ViewsHtm
        {
            get { return _viewshtm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TPX_0015_BackgroundServicesRepositoryFolders
    {
        /// <summary>
        /// The ServicesAppFolder folder.
        /// </summary>
        [RepositoryFolder("6ad69b29-6ebc-4115-a2df-c041640d3308")]
        public partial class ServicesAppFolder : RepoGenBaseFolder
        {
            TPX_0015_BackgroundServicesRepositoryFolders.Table12786Folder _table12786;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _buttonfileInfo;
            RepoItemInfo _pagedownInfo;
            RepoItemInfo _stopserviceInfo;
            RepoItemInfo _refreshInfo;

            /// <summary>
            /// Creates a new Services  folder.
            /// </summary>
            public ServicesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Services", "/form[@title='Services']", parentFolder, 30000, null, true, "6ad69b29-6ebc-4115-a2df-c041640d3308", "")
            {
                _table12786 = new TPX_0015_BackgroundServicesRepositoryFolders.Table12786Folder(this);
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@automationid='TitleBar']", "titlebar[@automationid='TitleBar']", 30000, null, "5d7f8422-be9e-4dcc-9b38-9bcc802b1f9a");
                _buttonfileInfo = new RepoItemInfo(this, "ButtonFile", ".//toolbar[@controlid='4097']/button[@text='&File']", ".//button[@text='&File']", 30000, null, "645b5b96-42f4-485e-97a9-a98151139ba5");
                _pagedownInfo = new RepoItemInfo(this, "PageDown", ".//table[@controlid='12786']/scrollbar[1]/button[@text='PageDown']", ".//button[@text='PageDown']", 30000, null, "de2cb2e9-6e33-46de-be9e-29c4c109f630");
                _stopserviceInfo = new RepoItemInfo(this, "StopService", ".//toolbar[@controlid='4098']/button[@text='Stop Service']", ".//button[@text='Stop Service']", 30000, null, "88b7aa54-ad25-457e-bbd2-f8353ad0d5d7");
                _refreshInfo = new RepoItemInfo(this, "Refresh", ".//toolbar[@controlid='4098']/button[@text='Refresh']", ".//button[@text='Refresh']", 30000, null, "f1d17480-bbb5-4380-b705-9065078508a0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ad69b29-6ebc-4115-a2df-c041640d3308")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ad69b29-6ebc-4115-a2df-c041640d3308")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("5d7f8422-be9e-4dcc-9b38-9bcc802b1f9a")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("5d7f8422-be9e-4dcc-9b38-9bcc802b1f9a")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The ButtonFile item.
            /// </summary>
            [RepositoryItem("645b5b96-42f4-485e-97a9-a98151139ba5")]
            public virtual Ranorex.Button ButtonFile
            {
                get
                {
                    return _buttonfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFile item info.
            /// </summary>
            [RepositoryItemInfo("645b5b96-42f4-485e-97a9-a98151139ba5")]
            public virtual RepoItemInfo ButtonFileInfo
            {
                get
                {
                    return _buttonfileInfo;
                }
            }

            /// <summary>
            /// The PageDown item.
            /// </summary>
            [RepositoryItem("de2cb2e9-6e33-46de-be9e-29c4c109f630")]
            public virtual Ranorex.Button PageDown
            {
                get
                {
                    return _pagedownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PageDown item info.
            /// </summary>
            [RepositoryItemInfo("de2cb2e9-6e33-46de-be9e-29c4c109f630")]
            public virtual RepoItemInfo PageDownInfo
            {
                get
                {
                    return _pagedownInfo;
                }
            }

            /// <summary>
            /// The StopService item.
            /// </summary>
            [RepositoryItem("88b7aa54-ad25-457e-bbd2-f8353ad0d5d7")]
            public virtual Ranorex.Button StopService
            {
                get
                {
                    return _stopserviceInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StopService item info.
            /// </summary>
            [RepositoryItemInfo("88b7aa54-ad25-457e-bbd2-f8353ad0d5d7")]
            public virtual RepoItemInfo StopServiceInfo
            {
                get
                {
                    return _stopserviceInfo;
                }
            }

            /// <summary>
            /// The Refresh item.
            /// </summary>
            [RepositoryItem("f1d17480-bbb5-4380-b705-9065078508a0")]
            public virtual Ranorex.Button Refresh
            {
                get
                {
                    return _refreshInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Refresh item info.
            /// </summary>
            [RepositoryItemInfo("f1d17480-bbb5-4380-b705-9065078508a0")]
            public virtual RepoItemInfo RefreshInfo
            {
                get
                {
                    return _refreshInfo;
                }
            }

            /// <summary>
            /// The Table12786 folder.
            /// </summary>
            [RepositoryFolder("7f6b6721-492f-44fb-b445-4d1017328782")]
            public virtual TPX_0015_BackgroundServicesRepositoryFolders.Table12786Folder Table12786
            {
                get { return _table12786; }
            }
        }

        /// <summary>
        /// The Table12786Folder folder.
        /// </summary>
        [RepositoryFolder("7f6b6721-492f-44fb-b445-4d1017328782")]
        public partial class Table12786Folder : RepoGenBaseFolder
        {
            RepoItemInfo _running2Info;
            RepoItemInfo _epxdicomserviceInfo;
            RepoItemInfo _running1Info;
            RepoItemInfo _epxpatientserviceInfo;
            RepoItemInfo _runningInfo;
            RepoItemInfo _epxsystemwinserviceInfo;
            RepoItemInfo _somecellInfo;

            /// <summary>
            /// Creates a new Table12786  folder.
            /// </summary>
            public Table12786Folder(RepoGenBaseFolder parentFolder) :
                    base("Table12786", ".//table[@controlid='12786']", parentFolder, 30000, null, false, "7f6b6721-492f-44fb-b445-4d1017328782", "")
            {
                _running2Info = new RepoItemInfo(this, "Running2", "row[@index='74']/cell[@text='Running']", "", 30000, null, "82cb7b6b-59c9-41f6-b1ae-dd6d5f632ff7");
                _epxdicomserviceInfo = new RepoItemInfo(this, "EpxDICOMService", "row[@index='74']/cell[@text='epxDICOMService']", "", 30000, null, "a6cc0a6d-64b9-442d-a1c3-5e65ff530545");
                _running1Info = new RepoItemInfo(this, "Running1", "row[@index='75']/cell[@text='Running']", "", 30000, null, "b8a8e729-572e-4f37-a532-8f5f80e6a9f6");
                _epxpatientserviceInfo = new RepoItemInfo(this, "EpxPatientService", "row[@index='75']/cell[@text='epxPatientService']", "", 30000, null, "fb4a9da4-f1bf-4c98-851c-a566c724e0a4");
                _runningInfo = new RepoItemInfo(this, "Running", "row[@index='76']/cell[@text='Running']", "", 30000, null, "4ea929ac-b0f1-4f74-be62-fad3eddfeb91");
                _epxsystemwinserviceInfo = new RepoItemInfo(this, "EpxSystemWinService", "row[@index='76']/cell[@text='epxSystemWinService']", "", 30000, null, "18071d04-d3c9-40e4-99e2-6e6372df8ad7");
                _somecellInfo = new RepoItemInfo(this, "SomeCell", "row[@index='74']/cell[@text='']", "", 30000, null, "717eec14-6b6c-4a7e-b44d-161f21995999");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f6b6721-492f-44fb-b445-4d1017328782")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f6b6721-492f-44fb-b445-4d1017328782")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Running2 item.
            /// </summary>
            [RepositoryItem("82cb7b6b-59c9-41f6-b1ae-dd6d5f632ff7")]
            public virtual Ranorex.Cell Running2
            {
                get
                {
                    return _running2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Running2 item info.
            /// </summary>
            [RepositoryItemInfo("82cb7b6b-59c9-41f6-b1ae-dd6d5f632ff7")]
            public virtual RepoItemInfo Running2Info
            {
                get
                {
                    return _running2Info;
                }
            }

            /// <summary>
            /// The EpxDICOMService item.
            /// </summary>
            [RepositoryItem("a6cc0a6d-64b9-442d-a1c3-5e65ff530545")]
            public virtual Ranorex.Cell EpxDICOMService
            {
                get
                {
                    return _epxdicomserviceInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The EpxDICOMService item info.
            /// </summary>
            [RepositoryItemInfo("a6cc0a6d-64b9-442d-a1c3-5e65ff530545")]
            public virtual RepoItemInfo EpxDICOMServiceInfo
            {
                get
                {
                    return _epxdicomserviceInfo;
                }
            }

            /// <summary>
            /// The Running1 item.
            /// </summary>
            [RepositoryItem("b8a8e729-572e-4f37-a532-8f5f80e6a9f6")]
            public virtual Ranorex.Cell Running1
            {
                get
                {
                    return _running1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Running1 item info.
            /// </summary>
            [RepositoryItemInfo("b8a8e729-572e-4f37-a532-8f5f80e6a9f6")]
            public virtual RepoItemInfo Running1Info
            {
                get
                {
                    return _running1Info;
                }
            }

            /// <summary>
            /// The EpxPatientService item.
            /// </summary>
            [RepositoryItem("fb4a9da4-f1bf-4c98-851c-a566c724e0a4")]
            public virtual Ranorex.Cell EpxPatientService
            {
                get
                {
                    return _epxpatientserviceInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The EpxPatientService item info.
            /// </summary>
            [RepositoryItemInfo("fb4a9da4-f1bf-4c98-851c-a566c724e0a4")]
            public virtual RepoItemInfo EpxPatientServiceInfo
            {
                get
                {
                    return _epxpatientserviceInfo;
                }
            }

            /// <summary>
            /// The Running item.
            /// </summary>
            [RepositoryItem("4ea929ac-b0f1-4f74-be62-fad3eddfeb91")]
            public virtual Ranorex.Cell Running
            {
                get
                {
                    return _runningInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Running item info.
            /// </summary>
            [RepositoryItemInfo("4ea929ac-b0f1-4f74-be62-fad3eddfeb91")]
            public virtual RepoItemInfo RunningInfo
            {
                get
                {
                    return _runningInfo;
                }
            }

            /// <summary>
            /// The EpxSystemWinService item.
            /// </summary>
            [RepositoryItem("18071d04-d3c9-40e4-99e2-6e6372df8ad7")]
            public virtual Ranorex.Cell EpxSystemWinService
            {
                get
                {
                    return _epxsystemwinserviceInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The EpxSystemWinService item info.
            /// </summary>
            [RepositoryItemInfo("18071d04-d3c9-40e4-99e2-6e6372df8ad7")]
            public virtual RepoItemInfo EpxSystemWinServiceInfo
            {
                get
                {
                    return _epxsystemwinserviceInfo;
                }
            }

            /// <summary>
            /// The SomeCell item.
            /// </summary>
            [RepositoryItem("717eec14-6b6c-4a7e-b44d-161f21995999")]
            public virtual Ranorex.Cell SomeCell
            {
                get
                {
                    return _somecellInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SomeCell item info.
            /// </summary>
            [RepositoryItemInfo("717eec14-6b6c-4a7e-b44d-161f21995999")]
            public virtual RepoItemInfo SomeCellInfo
            {
                get
                {
                    return _somecellInfo;
                }
            }
        }

        /// <summary>
        /// The ContextMenuMmcAppFolder folder.
        /// </summary>
        [RepositoryFolder("542cbbcc-d08a-4d53-a2c1-bed354135c28")]
        public partial class ContextMenuMmcAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new ContextMenuMmc  folder.
            /// </summary>
            public ContextMenuMmcAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextMenuMmc", "/contextmenu[@processname='mmc']", parentFolder, 30000, null, false, "542cbbcc-d08a-4d53-a2c1-bed354135c28", "")
            {
                _exitInfo = new RepoItemInfo(this, "Exit", "?/?/menuitem[@accessiblename='Exit']", "?/?/menuitem[@accessiblename='Exit']", 30000, null, "97cf0041-8bff-40d3-bdf3-45e1cba439c7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("542cbbcc-d08a-4d53-a2c1-bed354135c28")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("542cbbcc-d08a-4d53-a2c1-bed354135c28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("97cf0041-8bff-40d3-bdf3-45e1cba439c7")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("97cf0041-8bff-40d3-bdf3-45e1cba439c7")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The ViewsHtmAppFolder folder.
        /// </summary>
        [RepositoryFolder("efaa0d0b-23f5-41a0-98e3-45b49e869991")]
        public partial class ViewsHtmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _restartInfo;

            /// <summary>
            /// Creates a new ViewsHtm  folder.
            /// </summary>
            public ViewsHtmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ViewsHtm", "/dom[@domain='']", parentFolder, 30000, null, false, "efaa0d0b-23f5-41a0-98e3-45b49e869991", "")
            {
                _restartInfo = new RepoItemInfo(this, "Restart", ".//span[#'DetailsElem']/a[@innertext='Restart']", ".//span[#'DetailsElem']/a[@innertext='Restart']", 30000, null, "91944182-b780-4865-9fc0-42cff4a64744");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efaa0d0b-23f5-41a0-98e3-45b49e869991")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efaa0d0b-23f5-41a0-98e3-45b49e869991")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Restart item.
            /// </summary>
            [RepositoryItem("91944182-b780-4865-9fc0-42cff4a64744")]
            public virtual Ranorex.ATag Restart
            {
                get
                {
                    return _restartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Restart item info.
            /// </summary>
            [RepositoryItemInfo("91944182-b780-4865-9fc0-42cff4a64744")]
            public virtual RepoItemInfo RestartInfo
            {
                get
                {
                    return _restartInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
