///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0006_XML_Test_Files
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClosePlanningLic recording.
    /// </summary>
    [TestModule("f3da6038-e8ab-4000-bb48-8db4fed46c17", ModuleType.Recording, 1)]
    public partial class ClosePlanningLic : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0006_XML_Test_FilesRepository repository.
        /// </summary>
        public static TPX_0006_XML_Test_FilesRepository repo = TPX_0006_XML_Test_FilesRepository.Instance;

        static ClosePlanningLic instance = new ClosePlanningLic();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClosePlanningLic()
        {
            PlanningLicProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClosePlanningLic Instance
        {
            get { return instance; }
        }

#region Variables

        string _PlanningLicProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable PlanningLicProcessIDVar.
        /// </summary>
        [TestVariable("36b966d9-f832-47ee-8d95-c1e02dfafba2")]
        public string PlanningLicProcessIDVar
        {
            get { return _PlanningLicProcessIDVar; }
            set { _PlanningLicProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $PlanningLicProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(PlanningLicProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
