///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0006_XML_Test_Files
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseHTGLic recording.
    /// </summary>
    [TestModule("f62e903b-87ed-4053-bb24-4a8d4084754d", ModuleType.Recording, 1)]
    public partial class CloseHTGLic : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0006_XML_Test_FilesRepository repository.
        /// </summary>
        public static TPX_0006_XML_Test_FilesRepository repo = TPX_0006_XML_Test_FilesRepository.Instance;

        static CloseHTGLic instance = new CloseHTGLic();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseHTGLic()
        {
            HTGLicProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseHTGLic Instance
        {
            get { return instance; }
        }

#region Variables

        string _HTGLicProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable HTGLicProcessIDVar.
        /// </summary>
        [TestVariable("d351cedf-fe34-4004-8af2-42d43498b863")]
        public string HTGLicProcessIDVar
        {
            get { return _HTGLicProcessIDVar; }
            set { _HTGLicProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $HTGLicProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(HTGLicProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
