///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0006_XML_Test_Files
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SULic recording.
    /// </summary>
    [TestModule("5f33cd78-9530-493d-8f01-fbca504ef73a", ModuleType.Recording, 1)]
    public partial class SULic : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0006_XML_Test_FilesRepository repository.
        /// </summary>
        public static TPX_0006_XML_Test_FilesRepository repo = TPX_0006_XML_Test_FilesRepository.Instance;

        static SULic instance = new SULic();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SULic()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SULic Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Licenses_SUOnly
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Licenses_SUOnly", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Title='EchoPixel-SUOnly.lic') on item 'CEpxDataLicensingTestFilesEchoPixel.EchoPixelSUOnlyLic'.", repo.CEpxDataLicensingTestFilesEchoPixel.EchoPixelSUOnlyLicInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.CEpxDataLicensingTestFilesEchoPixel.EchoPixelSUOnlyLicInfo, "Title", "EchoPixel-SUOnly.lic");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (WindowText='LICENSE echopixel streamingus 1.0 31-dec-2099 uncounted hostid=ANY\r\n  _ck=c01efcc489 sig=\"60P04508N5R6DVS2TM3PBWDB2G5FMJ1N94TWQSG22G63784A\r\n  KFUPTM8PHGM8DV6B2Q1CS3NMN0\"\r\n') on item 'CEpxDataLicensingTestFilesEchoPixel.Scintilla'.", repo.CEpxDataLicensingTestFilesEchoPixel.ScintillaInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.CEpxDataLicensingTestFilesEchoPixel.ScintillaInfo, "WindowText", "LICENSE echopixel streamingus 1.0 31-dec-2099 uncounted hostid=ANY\r\n  _ck=c01efcc489 sig=\"60P04508N5R6DVS2TM3PBWDB2G5FMJ1N94TWQSG22G63784A\r\n  KFUPTM8PHGM8DV6B2Q1CS3NMN0\"\r\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CEpxDataLicensingTestFilesEchoPixel.Scintilla' at 181;446.", repo.CEpxDataLicensingTestFilesEchoPixel.ScintillaInfo, new RecordItemIndex(3));
            repo.CEpxDataLicensingTestFilesEchoPixel.Scintilla.Click("181;446");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press with focus on 'CEpxDataLicensingTestFilesEchoPixel.Scintilla'.", repo.CEpxDataLicensingTestFilesEchoPixel.ScintillaInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.CEpxDataLicensingTestFilesEchoPixel.Scintilla);
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, 17, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // VTP_Reference_Licenses_SUOnly
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Licenses_SUOnly", new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
