///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0006_XML_Test_Files
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The USErrGEVoluson3D recording.
    /// </summary>
    [TestModule("c5f8beca-3c46-4255-b988-59e50413748c", ModuleType.Recording, 1)]
    public partial class USErrGEVoluson3D : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0006_XML_Test_FilesRepository repository.
        /// </summary>
        public static TPX_0006_XML_Test_FilesRepository repo = TPX_0006_XML_Test_FilesRepository.Instance;

        static USErrGEVoluson3D instance = new USErrGEVoluson3D();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public USErrGEVoluson3D()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static USErrGEVoluson3D Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Scene_USError_GEVolusonVol
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Scene_USError_GEVolusonVol", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Title='GEVolusonVol.t3d') on item 'CEpxDataUSErrorScenesGEVolusonVolT3.GEVolusonVolT3d'.", repo.CEpxDataUSErrorScenesGEVolusonVolT3.GEVolusonVolT3dInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.CEpxDataUSErrorScenesGEVolusonVolT3.GEVolusonVolT3dInfo, "Title", "GEVolusonVol.t3d");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CEpxDataUSErrorScenesGEVolusonVolT3.Scintilla' at 363;552.", repo.CEpxDataUSErrorScenesGEVolusonVolT3.ScintillaInfo, new RecordItemIndex(2));
            repo.CEpxDataUSErrorScenesGEVolusonVolT3.Scintilla.Click("363;552");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press with focus on 'CEpxDataUSErrorScenesGEVolusonVolT3.Scintilla'.", repo.CEpxDataUSErrorScenesGEVolusonVolT3.ScintillaInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.CEpxDataUSErrorScenesGEVolusonVolT3.Scintilla);
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, 17, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // VTP_Reference_Scene_USError_GEVolusonVol
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Scene_USError_GEVolusonVol", new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
