///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnhancedData recording.
    /// </summary>
    [TestModule("0028b163-78d4-4052-b668-17243ff36f08", ModuleType.Recording, 1)]
    public partial class EnhancedData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static EnhancedData instance = new EnhancedData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnhancedData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnhancedData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_Enhanced
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_Enhanced", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.OrgNrgDcmDbFileSetAt389e76c7' at 9;10.", repo.DicomBrowser.OrgNrgDcmDbFileSetAt389e76c7Info, new RecordItemIndex(1));
            repo.DicomBrowser.OrgNrgDcmDbFileSetAt389e76c7.Click("9;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 28;25.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(2));
            repo.DicomBrowser.Tree.Click("28;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 76;39.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(3));
            repo.DicomBrowser.Tree.Click("76;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row26.Cell00100010'.", repo.DicomBrowser.Row26.Cell00100010Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row26.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row26.PatientsName'.", repo.DicomBrowser.Row26.PatientsNameInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row26.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='EnhancedCTData') on item 'DicomBrowser.Row26.EnhancedCTData'.", repo.DicomBrowser.Row26.EnhancedCTDataInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row26.EnhancedCTDataInfo, "Text", "EnhancedCTData");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0016)') on item 'DicomBrowser.Row1.Cell00080016'.", repo.DicomBrowser.Row1.Cell00080016Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row1.Cell00080016Info, "Text", "(0008,0016)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SOP Class UID') on item 'DicomBrowser.Row1.SOPClassUID'.", repo.DicomBrowser.Row1.SOPClassUIDInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row1.SOPClassUIDInfo, "Text", "SOP Class UID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1.2.840.10008.5.1.4.1.1.2.1') on item 'DicomBrowser.Row1.Cell12840100085141121'.", repo.DicomBrowser.Row1.Cell12840100085141121Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row1.Cell12840100085141121Info, "Text", "1.2.840.10008.5.1.4.1.1.2.1");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_Enhanced
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_Enhanced", new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
