///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GEDopplerVolume recording.
    /// </summary>
    [TestModule("f57962d3-c0c2-4b63-aaa8-ab9122247329", ModuleType.Recording, 1)]
    public partial class GEDopplerVolume : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static GEDopplerVolume instance = new GEDopplerVolume();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GEDopplerVolume()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GEDopplerVolume Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_Ultrasound_GEDopplerVolume
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_Ultrasound_GEDopplerVolume", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientTestDopplerVolume' at 44;8.", repo.DicomBrowser.PatientTestDopplerVolumeInfo, new RecordItemIndex(1));
            repo.DicomBrowser.PatientTestDopplerVolume.Click("44;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row19.Cell00100010'.", repo.DicomBrowser.Row19.Cell00100010Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DicomBrowser.Row19.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row19.PatientsName'.", repo.DicomBrowser.Row19.PatientsNameInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row19.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='GEDoppler_Volume') on item 'DicomBrowser.Row19.SomeCell2'.", repo.DicomBrowser.Row19.SomeCell2Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row19.SomeCell2Info, "Text", "GEDoppler_Volume");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0016)') on item 'DicomBrowser.Row2.Cell00080016'.", repo.DicomBrowser.Row2.Cell00080016Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.Cell00080016Info, "Text", "(0008,0016)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SOP Class UID') on item 'DicomBrowser.Row2.SOPClassUID'.", repo.DicomBrowser.Row2.SOPClassUIDInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.SOPClassUIDInfo, "Text", "SOP Class UID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1.2.840.10008.5.1.4.1.1.6.2') on item 'DicomBrowser.Row2.Cell12840100085141162'.", repo.DicomBrowser.Row2.Cell12840100085141162Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.Cell12840100085141162Info, "Text", "1.2.840.10008.5.1.4.1.1.6.2");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_Ultrasound_GEDopplerVolume
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_Ultrasound_GEDopplerVolume", new RecordItemIndex(8));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
