///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MultipleStudies recording.
    /// </summary>
    [TestModule("57b9f847-d4ca-4a1f-954e-6ae824f54cc8", ModuleType.Recording, 1)]
    public partial class MultipleStudies : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static MultipleStudies instance = new MultipleStudies();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MultipleStudies()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MultipleStudies Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_MultipleStudies
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_MultipleStudies", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientStudy1' at 59;10.", repo.DicomBrowser.PatientStudy1Info, new RecordItemIndex(1));
            repo.DicomBrowser.PatientStudy1.Click("59;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0020)') on item 'DicomBrowser.Row33.Cell00100020'.", repo.DicomBrowser.Row33.Cell00100020Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.Cell00100020Info, "Text", "(0010,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient ID') on item 'DicomBrowser.Row33.PatientID'.", repo.DicomBrowser.Row33.PatientIDInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.PatientIDInfo, "Text", "Patient ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study_1') on item 'DicomBrowser.Row33.Study1'.", repo.DicomBrowser.Row33.Study1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.Study1Info, "Text", "Study_1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 11;719.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(5));
            repo.DicomBrowser.VerticalScrollBar.Click("11;719");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 11;719.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(6));
            repo.DicomBrowser.VerticalScrollBar.Click("11;719");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0020,0010)') on item 'DicomBrowser.Row168.Cell00200010'.", repo.DicomBrowser.Row168.Cell00200010Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row168.Cell00200010Info, "Text", "(0020,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study ID') on item 'DicomBrowser.Row168.StudyID'.", repo.DicomBrowser.Row168.StudyIDInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row168.StudyIDInfo, "Text", "Study ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='3410') on item 'DicomBrowser.Row168.Cell3410'.", repo.DicomBrowser.Row168.Cell3410Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row168.Cell3410Info, "Text", "3410");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 72;28.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(10));
            repo.DicomBrowser.Tree.Click("72;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 10;21.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(11));
            repo.DicomBrowser.VerticalScrollBar.Click("10;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 9;21.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(12));
            repo.DicomBrowser.VerticalScrollBar.Click("9;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0020)') on item 'DicomBrowser.Row41.Cell00100020'.", repo.DicomBrowser.Row41.Cell00100020Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.DicomBrowser.Row41.Cell00100020Info, "Text", "(0010,0020)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient ID') on item 'DicomBrowser.Row41.PatientID'.", repo.DicomBrowser.Row41.PatientIDInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.DicomBrowser.Row41.PatientIDInfo, "Text", "Patient ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Study_2') on item 'DicomBrowser.Row41.Study2'.", repo.DicomBrowser.Row41.Study2Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.DicomBrowser.Row41.Study2Info, "Text", "Study_2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 13;807.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(16));
            repo.DicomBrowser.VerticalScrollBar.Click("13;807");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 13;807.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(17));
            repo.DicomBrowser.VerticalScrollBar.Click("13;807");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 13;807.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(18));
            repo.DicomBrowser.VerticalScrollBar.Click("13;807");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0020,0011)') on item 'DicomBrowser.Row185.Cell00200011'.", repo.DicomBrowser.Row185.Cell00200011Info, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.DicomBrowser.Row185.Cell00200011Info, "Text", "(0020,0011)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Series Number') on item 'DicomBrowser.Row185.SeriesNumber'.", repo.DicomBrowser.Row185.SeriesNumberInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DicomBrowser.Row185.SeriesNumberInfo, "Text", "Series Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='5330') on item 'DicomBrowser.Row185.Cell5330'.", repo.DicomBrowser.Row185.Cell5330Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.DicomBrowser.Row185.Cell5330Info, "Text", "5330");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_MultipleStudies
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_MultipleStudies", new RecordItemIndex(22));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
