///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NominalPercentage4D recording.
    /// </summary>
    [TestModule("ca162d6e-3a7a-4720-8789-87bcd94fd123", ModuleType.Recording, 1)]
    public partial class NominalPercentage4D : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static NominalPercentage4D instance = new NominalPercentage4D();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NominalPercentage4D()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NominalPercentage4D Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_4DNominalPercentage
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_4DNominalPercentage", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.OrgNrgDcmDbFileSetAt74b383d1' at 6;10.", repo.DicomBrowser.OrgNrgDcmDbFileSetAt74b383d1Info, new RecordItemIndex(1));
            repo.DicomBrowser.OrgNrgDcmDbFileSetAt74b383d1.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 27;24.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(2));
            repo.DicomBrowser.Tree.Click("27;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 106;39.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(3));
            repo.DicomBrowser.Tree.Click("106;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row33.Cell00100010'.", repo.DicomBrowser.Row33.Cell00100010Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row33.PatientsName'.", repo.DicomBrowser.Row33.PatientsNameInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4DDataNominalPercentage') on item 'DicomBrowser.Row33.Cell4DDataNominalPercentage'.", repo.DicomBrowser.Row33.Cell4DDataNominalPercentageInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row33.Cell4DDataNominalPercentageInfo, "Text", "4DDataNominalPercentage");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 11;552.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(7));
            repo.DicomBrowser.VerticalScrollBar.Click("11;552");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0020,9241)') on item 'DicomBrowser.Row101.Cell00209241'.", repo.DicomBrowser.Row101.Cell00209241Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row101.Cell00209241Info, "Text", "(0020,9241)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Nominal Percentage of Cardiac Phase') on item 'DicomBrowser.Row101.NominalPercentageOfCardiacPhase'.", repo.DicomBrowser.Row101.NominalPercentageOfCardiacPhaseInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row101.NominalPercentageOfCardiacPhaseInfo, "Text", "Nominal Percentage of Cardiac Phase");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='8 values: 15.0, 20.0, 25.0, 30.0...') on item 'DicomBrowser.Row101.Cell8Values150200250300'.", repo.DicomBrowser.Row101.Cell8Values150200250300Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row101.Cell8Values150200250300Info, "Text", "8 values: 15.0, 20.0, 25.0, 30.0...");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_4DNominalPercentage
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_4DNominalPercentage", new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
