///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartUSPH recording.
    /// </summary>
    [TestModule("caf92938-5b19-41b7-a158-b0d163053d83", ModuleType.Recording, 1)]
    public partial class StartUSPH : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static StartUSPH instance = new StartUSPH();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartUSPH()
        {
            USPHProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartUSPH Instance
        {
            get { return instance; }
        }

#region Variables

        string _USPHProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable USPHProcessIDVar.
        /// </summary>
        [TestVariable("96f77e50-146c-4494-bec7-f9d469e78617")]
        public string USPHProcessIDVar
        {
            get { return _USPHProcessIDVar; }
            set { _USPHProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"' with arguments '\"C:\\epxData\\devImages\\Philips_Ultrasound\"' in normal mode. Return value bound to $USPHProcessIDVar.", new RecordItemIndex(0));
            USPHProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"", "\"C:\\epxData\\devImages\\Philips_Ultrasound\"", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser.DicomBrowser' at 353;0.", repo.DicomBrowser.DicomBrowserInfo, new RecordItemIndex(1));
            repo.DicomBrowser.DicomBrowser.DoubleClick("353;0");
            Delay.Milliseconds(0);
            
            // Start app & Open Data - VTP_Reference_Data_Ultrasound_PH
            Report.Log(ReportLevel.Info, "User", "Start app & Open Data - VTP_Reference_Data_Ultrasound_PH", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
