///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartTriggerTime4D recording.
    /// </summary>
    [TestModule("3e93dc9d-ca14-4654-93bd-eaf8fd3fd55a", ModuleType.Recording, 1)]
    public partial class StartTriggerTime4D : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static StartTriggerTime4D instance = new StartTriggerTime4D();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartTriggerTime4D()
        {
            TriggerTime4DProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartTriggerTime4D Instance
        {
            get { return instance; }
        }

#region Variables

        string _TriggerTime4DProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable TriggerTime4DProcessIDVar.
        /// </summary>
        [TestVariable("91a72907-e597-4120-a142-ddb584442f74")]
        public string TriggerTime4DProcessIDVar
        {
            get { return _TriggerTime4DProcessIDVar; }
            set { _TriggerTime4DProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"' with arguments '\"C:\\epxData\\devImages\\4DTriggerTime\"' in normal mode. Return value bound to $TriggerTime4DProcessIDVar.", new RecordItemIndex(0));
            TriggerTime4DProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"", "\"C:\\epxData\\devImages\\4DTriggerTime\"", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser.DicomBrowser' at 353;0.", repo.DicomBrowser.DicomBrowserInfo, new RecordItemIndex(1));
            repo.DicomBrowser.DicomBrowser.DoubleClick("353;0");
            Delay.Milliseconds(0);
            
            // Start app & Open Data - VTP_Reference_Data_4DTriggerTime
            Report.Log(ReportLevel.Info, "User", "Start app & Open Data - VTP_Reference_Data_4DTriggerTime", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
