///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartMultStudies recording.
    /// </summary>
    [TestModule("2fe277a2-5982-4f55-9bb3-14b3b15e92f9", ModuleType.Recording, 1)]
    public partial class StartMultStudies : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static StartMultStudies instance = new StartMultStudies();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartMultStudies()
        {
            MultStudiesProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartMultStudies Instance
        {
            get { return instance; }
        }

#region Variables

        string _MultStudiesProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable MultStudiesProcessIDVar.
        /// </summary>
        [TestVariable("f143c20e-5e4b-484b-9ee5-9695f2ea184b")]
        public string MultStudiesProcessIDVar
        {
            get { return _MultStudiesProcessIDVar; }
            set { _MultStudiesProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"' with arguments '\"C:\\epxData\\devImages\\DataSet_MultipleStudies\"' in normal mode. Return value bound to $MultStudiesProcessIDVar.", new RecordItemIndex(0));
            MultStudiesProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\dicombrowser\\bin\\DicomBrowser.exe\"", "\"C:\\epxData\\devImages\\DataSet_MultipleStudies\"", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DicomBrowser.DicomBrowser' at 353;0.", repo.DicomBrowser.DicomBrowserInfo, new RecordItemIndex(1));
            repo.DicomBrowser.DicomBrowser.DoubleClick("353;0");
            Delay.Milliseconds(0);
            
            // Start app & Open Data - VTP_Reference_Data_MultipleStudies
            Report.Log(ReportLevel.Info, "User", "Start app & Open Data - VTP_Reference_Data_MultipleStudies", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
