///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TemporalPosition recording.
    /// </summary>
    [TestModule("7736b4e7-c12f-43d0-b025-d30519cd7a7f", ModuleType.Recording, 1)]
    public partial class TemporalPosition : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static TemporalPosition instance = new TemporalPosition();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TemporalPosition()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TemporalPosition Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_4DTemporalPosition
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_4DTemporalPosition", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.OrgNrgDcmDbFileSetAt883e8244' at 8;10.", repo.DicomBrowser.OrgNrgDcmDbFileSetAt883e8244Info, new RecordItemIndex(1));
            repo.DicomBrowser.OrgNrgDcmDbFileSetAt883e8244.Click("8;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 24;25.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(2));
            repo.DicomBrowser.Tree.Click("24;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.Tree' at 77;42.", repo.DicomBrowser.TreeInfo, new RecordItemIndex(3));
            repo.DicomBrowser.Tree.Click("77;42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row37.Cell00100010'.", repo.DicomBrowser.Row37.Cell00100010Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row37.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row37.PatientsName'.", repo.DicomBrowser.Row37.PatientsNameInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row37.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4DData_TemporalPosition') on item 'DicomBrowser.Row37.Cell4DDataTemporalPosition'.", repo.DicomBrowser.Row37.Cell4DDataTemporalPositionInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row37.Cell4DDataTemporalPositionInfo, "Text", "4DData_TemporalPosition");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 8;749.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(7));
            repo.DicomBrowser.VerticalScrollBar.Click("8;749");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 8;749.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(8));
            repo.DicomBrowser.VerticalScrollBar.Click("8;749");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.VerticalScrollBar' at 8;749.", repo.DicomBrowser.VerticalScrollBarInfo, new RecordItemIndex(9));
            repo.DicomBrowser.VerticalScrollBar.Click("8;749");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0020,0100)') on item 'DicomBrowser.Row184.Cell00200100'.", repo.DicomBrowser.Row184.Cell00200100Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row184.Cell00200100Info, "Text", "(0020,0100)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Temporal Position Identifier') on item 'DicomBrowser.Row184.TemporalPositionIdentifier'.", repo.DicomBrowser.Row184.TemporalPositionIdentifierInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.DicomBrowser.Row184.TemporalPositionIdentifierInfo, "Text", "Temporal Position Identifier");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='60 values: 1, 2, 3, 4...') on item 'DicomBrowser.Row184.Cell60Values1234'.", repo.DicomBrowser.Row184.Cell60Values1234Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.DicomBrowser.Row184.Cell60Values1234Info, "Text", "60 values: 1, 2, 3, 4...");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_4DTemporalPosition
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_4DTemporalPosition", new RecordItemIndex(13));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
