///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0004_TestData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The XACine recording.
    /// </summary>
    [TestModule("c69c15cc-afb9-4d3b-bc1e-f86666bb610e", ModuleType.Recording, 1)]
    public partial class XACine : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0004_TestDataRepository repository.
        /// </summary>
        public static TPX_0004_TestDataRepository repo = TPX_0004_TestDataRepository.Instance;

        static XACine instance = new XACine();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public XACine()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static XACine Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // VTP_Reference_Data_XACine
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_XACine", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DicomBrowser.PatientXAVerification' at 33;9.", repo.DicomBrowser.PatientXAVerificationInfo, new RecordItemIndex(1));
            repo.DicomBrowser.PatientXAVerification.Click("33;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0010,0010)') on item 'DicomBrowser.Row25.Cell00100010'.", repo.DicomBrowser.Row25.Cell00100010Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DicomBrowser.Row25.Cell00100010Info, "Text", "(0010,0010)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Patient’s Name') on item 'DicomBrowser.Row25.PatientsName'.", repo.DicomBrowser.Row25.PatientsNameInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DicomBrowser.Row25.PatientsNameInfo, "Text", "Patient’s Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='XA_CineDataSet') on item 'DicomBrowser.Row25.XACineDataSet'.", repo.DicomBrowser.Row25.XACineDataSetInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DicomBrowser.Row25.XACineDataSetInfo, "Text", "XA_CineDataSet");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0008,0016)') on item 'DicomBrowser.Row2.Cell00080016'.", repo.DicomBrowser.Row2.Cell00080016Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.Cell00080016Info, "Text", "(0008,0016)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SOP Class UID') on item 'DicomBrowser.Row2.SOPClassUID'.", repo.DicomBrowser.Row2.SOPClassUIDInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.SOPClassUIDInfo, "Text", "SOP Class UID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1.2.840.10008.5.1.4.1.1.12.1') on item 'DicomBrowser.Row2.Cell128401000851411121'.", repo.DicomBrowser.Row2.Cell128401000851411121Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DicomBrowser.Row2.Cell128401000851411121Info, "Text", "1.2.840.10008.5.1.4.1.1.12.1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(0018,115E)') on item 'DicomBrowser.Row44.Cell0018115E'.", repo.DicomBrowser.Row44.Cell0018115EInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DicomBrowser.Row44.Cell0018115EInfo, "Text", "(0018,115E)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Image and Fluoroscopy Area Dose Product') on item 'DicomBrowser.Row44.ImageAndFluoroscopyAreaDoseProduct'.", repo.DicomBrowser.Row44.ImageAndFluoroscopyAreaDoseProductInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DicomBrowser.Row44.ImageAndFluoroscopyAreaDoseProductInfo, "Text", "Image and Fluoroscopy Area Dose Product");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4 values: 0.021, 0.04, 0.056, 0.048') on item 'DicomBrowser.Row44.Cell4Values002100400560048'.", repo.DicomBrowser.Row44.Cell4Values002100400560048Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.DicomBrowser.Row44.Cell4Values002100400560048Info, "Text", "4 values: 0.021, 0.04, 0.056, 0.048");
            Delay.Milliseconds(100);
            
            // VTP_Reference_Data_XACine
            Report.Log(ReportLevel.Info, "User", "VTP_Reference_Data_XACine", new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
