///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0005_SurfaceTestFiles
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseSphere20 recording.
    /// </summary>
    [TestModule("c563b18e-3748-4e0d-9f87-6910e563431b", ModuleType.Recording, 1)]
    public partial class CloseSphere20 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0005_SurfaceTestFilesRepository repository.
        /// </summary>
        public static TPX_0005_SurfaceTestFilesRepository repo = TPX_0005_SurfaceTestFilesRepository.Instance;

        static CloseSphere20 instance = new CloseSphere20();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseSphere20()
        {
            Sphere20ProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseSphere20 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Sphere20ProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable Sphere20ProcessIDVar.
        /// </summary>
        [TestVariable("ca0b9c0b-30ae-4c4f-86a2-6570ceeadfbf")]
        public string Sphere20ProcessIDVar
        {
            get { return _Sphere20ProcessIDVar; }
            set { _Sphere20ProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $Sphere20ProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(Sphere20ProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
