///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0005_SurfaceTestFiles
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseSphere5 recording.
    /// </summary>
    [TestModule("0a714606-0605-4ad2-a02d-935339276df2", ModuleType.Recording, 1)]
    public partial class CloseSphere5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0005_SurfaceTestFilesRepository repository.
        /// </summary>
        public static TPX_0005_SurfaceTestFilesRepository repo = TPX_0005_SurfaceTestFilesRepository.Instance;

        static CloseSphere5 instance = new CloseSphere5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseSphere5()
        {
            Sphere5ProcessIDVar = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseSphere5 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Sphere5ProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable Sphere5ProcessIDVar.
        /// </summary>
        [TestVariable("868ce5a8-97bc-4b86-a26c-85a3cf26de68")]
        public string Sphere5ProcessIDVar
        {
            get { return _Sphere5ProcessIDVar; }
            set { _Sphere5ProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application with Process ID bound to variable $Sphere5ProcessIDVar.", new RecordItemIndex(0));
            Host.Current.CloseApplication(int.Parse(Sphere5ProcessIDVar), 500);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
