///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0005_SurfaceTestFiles
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartCenterlineErr recording.
    /// </summary>
    [TestModule("2ad678e8-bb27-4db2-b174-44448e7a1a16", ModuleType.Recording, 1)]
    public partial class StartCenterlineErr : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0005_SurfaceTestFilesRepository repository.
        /// </summary>
        public static TPX_0005_SurfaceTestFilesRepository repo = TPX_0005_SurfaceTestFilesRepository.Instance;

        static StartCenterlineErr instance = new StartCenterlineErr();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartCenterlineErr()
        {
            CenterlineErrProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartCenterlineErr Instance
        {
            get { return instance; }
        }

#region Variables

        string _CenterlineErrProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable CenterlineErrProcessIDVar.
        /// </summary>
        [TestVariable("de4611e2-24e6-423e-bd4d-30dcdb6d3b41")]
        public string CenterlineErrProcessIDVar
        {
            get { return _CenterlineErrProcessIDVar; }
            set { _CenterlineErrProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\Autodesk\\Meshmixer\\meshmixer.exe\"' with arguments '\"C:\\epxData\\devImages\\CenterlineErrorVTP\\CenterlineError.stl\"' in maximized mode. Return value bound to $CenterlineErrProcessIDVar.", new RecordItemIndex(0));
            CenterlineErrProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\Autodesk\\Meshmixer\\meshmixer.exe\"", "\"C:\\epxData\\devImages\\CenterlineErrorVTP\\CenterlineError.stl\"", "C:\\Program Files\\Autodesk\\Meshmixer", true));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Start meshmixer.exe", new RecordItemIndex(1));
            
            // Open VTP_Reference_Data_STL_CenterlineError
            Report.Log(ReportLevel.Info, "User", "Open VTP_Reference_Data_STL_CenterlineError", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
