///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0005_SurfaceTestFiles
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartSphere20 recording.
    /// </summary>
    [TestModule("08e56783-8da8-4548-b1c3-bb18239ba9b0", ModuleType.Recording, 1)]
    public partial class StartSphere20 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0005_SurfaceTestFilesRepository repository.
        /// </summary>
        public static TPX_0005_SurfaceTestFilesRepository repo = TPX_0005_SurfaceTestFilesRepository.Instance;

        static StartSphere20 instance = new StartSphere20();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartSphere20()
        {
            Sphere20ProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartSphere20 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Sphere20ProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable Sphere20ProcessIDVar.
        /// </summary>
        [TestVariable("c7626277-bcea-495c-b144-3f6caaf9ada5")]
        public string Sphere20ProcessIDVar
        {
            get { return _Sphere20ProcessIDVar; }
            set { _Sphere20ProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\"C:\\Program Files\\Autodesk\\Meshmixer\\meshmixer.exe\"' with arguments '\"C:\\epxData\\devImages\\Shapes_STL\\Sphere_20mm.stl\"' in maximized mode. Return value bound to $Sphere20ProcessIDVar.", new RecordItemIndex(0));
            Sphere20ProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("\"C:\\Program Files\\Autodesk\\Meshmixer\\meshmixer.exe\"", "\"C:\\epxData\\devImages\\Shapes_STL\\Sphere_20mm.stl\"", "C:\\Program Files\\Autodesk\\Meshmixer", true));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Start meshmixer.exe", new RecordItemIndex(1));
            
            // Open VTP_Reference_Data_STL_Shapes_Sphere20
            Report.Log(ReportLevel.Info, "User", "Open VTP_Reference_Data_STL_Shapes_Sphere20", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
