///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TPX_0013_UserManual_JP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IDs recording.
    /// </summary>
    [TestModule("ee391fb9-6ec0-44b2-b092-020edfa70825", ModuleType.Recording, 1)]
    public partial class IDs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TPX_0013_UserManual_JPRepository repository.
        /// </summary>
        public static TPX_0013_UserManual_JPRepository repo = TPX_0013_UserManual_JPRepository.Instance;

        static IDs instance = new IDs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IDs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IDs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Confirm the User Manual version and identification details
            Report.Log(ReportLevel.Info, "User", "Confirm the User Manual version and identification details", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView' at 745;426.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(1));
            repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView.Click("745;426");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView1' at 979;722.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView1Info, new RecordItemIndex(2));
            repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView1.Click("979;722");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{Return}' with focus on 'LBL0050002BTrue3DT3DViewerUs'.", repo.LBL0050002BTrue3DT3DViewerUs.SelfInfo, new RecordItemIndex(3));
            repo.LBL0050002BTrue3DT3DViewerUs.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}{Return}");
            Delay.Milliseconds(0);
            
            // Software Version
            Report.Log(ReportLevel.Info, "User", "Software Version", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=434,Y=536,Width=257,Height=59}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(5));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot1, AVLAVView_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Version
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Version", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=143,Y=892,Width=199,Height=15}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(7));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot1_2, AVLAVView_Screenshot1_2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Version
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Version", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView' at 752;627.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(9));
            repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView.Click("752;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView1' at 983;725.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView1Info, new RecordItemIndex(10));
            repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView1.Click("983;725");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{Return}' with focus on 'LBL0050002BTrue3DT3DViewerUs'.", repo.LBL0050002BTrue3DT3DViewerUs.SelfInfo, new RecordItemIndex(11));
            repo.LBL0050002BTrue3DT3DViewerUs.Self.EnsureVisible();
            Keyboard.Press("{NumPad2}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView' at 765;686.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(12));
            repo.LBL0050002BTrue3DT3DViewerUs.AVLAVView.Click("765;686");
            Delay.Milliseconds(0);
            
            // Manufacturer
            Report.Log(ReportLevel.Info, "User", "Manufacturer", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=155,Y=126,Width=67,Height=63}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(14));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2, AVLAVView_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Manufacturer
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Manufacturer", new RecordItemIndex(15));
            
            // Address
            Report.Log(ReportLevel.Info, "User", "Address", new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=249,Y=125,Width=132,Height=65}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(17));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_2, AVLAVView_Screenshot2_2_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_Address
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_Address", new RecordItemIndex(18));
            
            // Country of Manufacture
            Report.Log(ReportLevel.Info, "User", "Country of Manufacture", new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=156,Y=198,Width=66,Height=64}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(20));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_3, AVLAVView_Screenshot2_3_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_ConutryOfManufacture
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_ConutryOfManufacture", new RecordItemIndex(21));
            
            // Medical Device
            Report.Log(ReportLevel.Info, "User", "Medical Device", new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=284,Y=211,Width=54,Height=38}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(23));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_4, AVLAVView_Screenshot2_4_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_MD
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_MD", new RecordItemIndex(24));
            
            // UDI
            Report.Log(ReportLevel.Info, "User", "UDI", new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=390,Y=210,Width=335,Height=41}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(26));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_5, AVLAVView_Screenshot2_5_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_UDI
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_UDI", new RecordItemIndex(27));
            
            // Part Number
            Report.Log(ReportLevel.Info, "User", "Part Number", new RecordItemIndex(28));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=387,Y=138,Width=265,Height=41}) on item 'LBL0050002BTrue3DT3DViewerUs.AVLAVView'.", repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, new RecordItemIndex(29));
            Validate.CompareImage(repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo, AVLAVView_Screenshot2_6, AVLAVView_Screenshot2_6_Options);
            Delay.Milliseconds(100);
            
            // VTP_Labeling_UserManual_PartNum
            Report.Log(ReportLevel.Info, "User", "VTP_Labeling_UserManual_PartNum", new RecordItemIndex(30));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot1
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot1(new Rectangle(434, 536, 257, 59)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;434,536,257,59;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot1_2
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot1(new Rectangle(143, 892, 199, 15)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Parse("0.99;None;143,892,199,15;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(155, 126, 67, 63)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;155,126,67,63;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_2
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(249, 125, 132, 65)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_2_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;249,125,132,65;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_3
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(156, 198, 66, 64)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_3_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;156,198,66,64;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_4
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(284, 211, 54, 38)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_4_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;284,211,54,38;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_5
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(390, 210, 335, 41)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_5_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;390,210,335,41;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AVLAVView_Screenshot2_6
        { get { return repo.LBL0050002BTrue3DT3DViewerUs.AVLAVViewInfo.GetScreenshot2(new Rectangle(387, 138, 265, 41)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AVLAVView_Screenshot2_6_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;387,138,265,41;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
